<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Enum\" />
    <None Remove="Respone\" />
    <None Remove="Respone\Account\" />
    <None Remove="Request\" />
    <None Remove="Table\" />
    <None Remove="Request\Account\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Enum\" />
    <Folder Include="Respone\Account\" />
    <Folder Include="Table\" />
    <Folder Include="Request\Account\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.7.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>
</Project>
