//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GipNcm_V2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GipNcm_V2.CA2_GIPSoap")]
    public interface CA2_GIPSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laythongtin_NNT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_NNTResponse> Laythongtin_NNTAsync(GipNcm_V2.Laythongtin_NNTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laythongtin_DBHC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DBHCResponse> Laythongtin_DBHCAsync(GipNcm_V2.Laythongtin_DBHCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laythongtin_LoaiNNT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_LoaiNNTResponse> Laythongtin_LoaiNNTAsync(GipNcm_V2.Laythongtin_LoaiNNTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laythongtin_DMCQT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DMCQTResponse> Laythongtin_DMCQTAsync(GipNcm_V2.Laythongtin_DMCQTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laythongtintaikhoan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.LaythongtintaikhoanResponse> LaythongtintaikhoanAsync(GipNcm_V2.LaythongtintaikhoanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hash256", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GipNcm_V2.hash256Response> hash256Async(GipNcm_V2.hash256Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApiAccount
    {
        
        private string taikhoanField;
        
        private string matkhauField;
        
        private string quyenField;
        
        private bool activeField;
        
        private int checkDLField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string taikhoan
        {
            get
            {
                return this.taikhoanField;
            }
            set
            {
                this.taikhoanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string matkhau
        {
            get
            {
                return this.matkhauField;
            }
            set
            {
                this.matkhauField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Quyen
        {
            get
            {
                return this.quyenField;
            }
            set
            {
                this.quyenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int CheckDL
        {
            get
            {
                return this.checkDLField;
            }
            set
            {
                this.checkDLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ThongtinNNT
    {
        
        private string mSTField;
        
        private string tEN_NNTField;
        
        private string lOAI_NNTField;
        
        private string tRANG_THAIField;
        
        private string tRANG_THAI_CTField;
        
        private string nGAYCAP_MSTField;
        
        private string cQT_QLField;
        
        private string tEN_CQTField;
        
        private string mOTA_DIACHIField;
        
        private string mA_TINHField;
        
        private string mA_HUYENField;
        
        private string mA_XAField;
        
        private string tEN_TINHField;
        
        private string tEN_HUYENField;
        
        private string tEN_XAField;
        
        private string dIACHI_DAYDUField;
        
        private int checkDLField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MST
        {
            get
            {
                return this.mSTField;
            }
            set
            {
                this.mSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TEN_NNT
        {
            get
            {
                return this.tEN_NNTField;
            }
            set
            {
                this.tEN_NNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LOAI_NNT
        {
            get
            {
                return this.lOAI_NNTField;
            }
            set
            {
                this.lOAI_NNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TRANG_THAI
        {
            get
            {
                return this.tRANG_THAIField;
            }
            set
            {
                this.tRANG_THAIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TRANG_THAI_CT
        {
            get
            {
                return this.tRANG_THAI_CTField;
            }
            set
            {
                this.tRANG_THAI_CTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NGAYCAP_MST
        {
            get
            {
                return this.nGAYCAP_MSTField;
            }
            set
            {
                this.nGAYCAP_MSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CQT_QL
        {
            get
            {
                return this.cQT_QLField;
            }
            set
            {
                this.cQT_QLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TEN_CQT
        {
            get
            {
                return this.tEN_CQTField;
            }
            set
            {
                this.tEN_CQTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MOTA_DIACHI
        {
            get
            {
                return this.mOTA_DIACHIField;
            }
            set
            {
                this.mOTA_DIACHIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MA_TINH
        {
            get
            {
                return this.mA_TINHField;
            }
            set
            {
                this.mA_TINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MA_HUYEN
        {
            get
            {
                return this.mA_HUYENField;
            }
            set
            {
                this.mA_HUYENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MA_XA
        {
            get
            {
                return this.mA_XAField;
            }
            set
            {
                this.mA_XAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TEN_TINH
        {
            get
            {
                return this.tEN_TINHField;
            }
            set
            {
                this.tEN_TINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TEN_HUYEN
        {
            get
            {
                return this.tEN_HUYENField;
            }
            set
            {
                this.tEN_HUYENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TEN_XA
        {
            get
            {
                return this.tEN_XAField;
            }
            set
            {
                this.tEN_XAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DIACHI_DAYDU
        {
            get
            {
                return this.dIACHI_DAYDUField;
            }
            set
            {
                this.dIACHI_DAYDUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int CheckDL
        {
            get
            {
                return this.checkDLField;
            }
            set
            {
                this.checkDLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_NNT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_NNTRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MST;
        
        public Laythongtin_NNTRequest()
        {
        }
        
        public Laythongtin_NNTRequest(GipNcm_V2.AuthHeader AuthHeader, string MST)
        {
            this.AuthHeader = AuthHeader;
            this.MST = MST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_NNTResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_NNTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GipNcm_V2.ThongtinNNT Laythongtin_NNTResult;
        
        public Laythongtin_NNTResponse()
        {
        }
        
        public Laythongtin_NNTResponse(GipNcm_V2.ThongtinNNT Laythongtin_NNTResult)
        {
            this.Laythongtin_NNTResult = Laythongtin_NNTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_DBHC", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_DBHCRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        public Laythongtin_DBHCRequest()
        {
        }
        
        public Laythongtin_DBHCRequest(GipNcm_V2.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_DBHCResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_DBHCResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Laythongtin_DBHCResult;
        
        public Laythongtin_DBHCResponse()
        {
        }
        
        public Laythongtin_DBHCResponse(string Laythongtin_DBHCResult)
        {
            this.Laythongtin_DBHCResult = Laythongtin_DBHCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_LoaiNNT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_LoaiNNTRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        public Laythongtin_LoaiNNTRequest()
        {
        }
        
        public Laythongtin_LoaiNNTRequest(GipNcm_V2.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_LoaiNNTResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_LoaiNNTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Laythongtin_LoaiNNTResult;
        
        public Laythongtin_LoaiNNTResponse()
        {
        }
        
        public Laythongtin_LoaiNNTResponse(string Laythongtin_LoaiNNTResult)
        {
            this.Laythongtin_LoaiNNTResult = Laythongtin_LoaiNNTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_DMCQT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_DMCQTRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        public Laythongtin_DMCQTRequest()
        {
        }
        
        public Laythongtin_DMCQTRequest(GipNcm_V2.AuthHeader AuthHeader)
        {
            this.AuthHeader = AuthHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtin_DMCQTResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Laythongtin_DMCQTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Laythongtin_DMCQTResult;
        
        public Laythongtin_DMCQTResponse()
        {
        }
        
        public Laythongtin_DMCQTResponse(string Laythongtin_DMCQTResult)
        {
            this.Laythongtin_DMCQTResult = Laythongtin_DMCQTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Laythongtintaikhoan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaythongtintaikhoanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string taikhoanin;
        
        public LaythongtintaikhoanRequest()
        {
        }
        
        public LaythongtintaikhoanRequest(GipNcm_V2.AuthHeader AuthHeader, string taikhoanin)
        {
            this.AuthHeader = AuthHeader;
            this.taikhoanin = taikhoanin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LaythongtintaikhoanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LaythongtintaikhoanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public GipNcm_V2.ApiAccount LaythongtintaikhoanResult;
        
        public LaythongtintaikhoanResponse()
        {
        }
        
        public LaythongtintaikhoanResponse(GipNcm_V2.ApiAccount LaythongtintaikhoanResult)
        {
            this.LaythongtintaikhoanResult = LaythongtintaikhoanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hash256", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class hash256Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public GipNcm_V2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string schuoi;
        
        public hash256Request()
        {
        }
        
        public hash256Request(GipNcm_V2.AuthHeader AuthHeader, string schuoi)
        {
            this.AuthHeader = AuthHeader;
            this.schuoi = schuoi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hash256Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class hash256Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string hash256Result;
        
        public hash256Response()
        {
        }
        
        public hash256Response(string hash256Result)
        {
            this.hash256Result = hash256Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CA2_GIPSoapChannel : GipNcm_V2.CA2_GIPSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CA2_GIPSoapClient : System.ServiceModel.ClientBase<GipNcm_V2.CA2_GIPSoap>, GipNcm_V2.CA2_GIPSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CA2_GIPSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CA2_GIPSoapClient.GetBindingForEndpoint(endpointConfiguration), CA2_GIPSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CA2_GIPSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CA2_GIPSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CA2_GIPSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CA2_GIPSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CA2_GIPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_NNTResponse> GipNcm_V2.CA2_GIPSoap.Laythongtin_NNTAsync(GipNcm_V2.Laythongtin_NNTRequest request)
        {
            return base.Channel.Laythongtin_NNTAsync(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_NNTResponse> Laythongtin_NNTAsync(GipNcm_V2.AuthHeader AuthHeader, string MST)
        {
            GipNcm_V2.Laythongtin_NNTRequest inValue = new GipNcm_V2.Laythongtin_NNTRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.MST = MST;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).Laythongtin_NNTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DBHCResponse> GipNcm_V2.CA2_GIPSoap.Laythongtin_DBHCAsync(GipNcm_V2.Laythongtin_DBHCRequest request)
        {
            return base.Channel.Laythongtin_DBHCAsync(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DBHCResponse> Laythongtin_DBHCAsync(GipNcm_V2.AuthHeader AuthHeader)
        {
            GipNcm_V2.Laythongtin_DBHCRequest inValue = new GipNcm_V2.Laythongtin_DBHCRequest();
            inValue.AuthHeader = AuthHeader;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).Laythongtin_DBHCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_LoaiNNTResponse> GipNcm_V2.CA2_GIPSoap.Laythongtin_LoaiNNTAsync(GipNcm_V2.Laythongtin_LoaiNNTRequest request)
        {
            return base.Channel.Laythongtin_LoaiNNTAsync(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_LoaiNNTResponse> Laythongtin_LoaiNNTAsync(GipNcm_V2.AuthHeader AuthHeader)
        {
            GipNcm_V2.Laythongtin_LoaiNNTRequest inValue = new GipNcm_V2.Laythongtin_LoaiNNTRequest();
            inValue.AuthHeader = AuthHeader;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).Laythongtin_LoaiNNTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DMCQTResponse> GipNcm_V2.CA2_GIPSoap.Laythongtin_DMCQTAsync(GipNcm_V2.Laythongtin_DMCQTRequest request)
        {
            return base.Channel.Laythongtin_DMCQTAsync(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.Laythongtin_DMCQTResponse> Laythongtin_DMCQTAsync(GipNcm_V2.AuthHeader AuthHeader)
        {
            GipNcm_V2.Laythongtin_DMCQTRequest inValue = new GipNcm_V2.Laythongtin_DMCQTRequest();
            inValue.AuthHeader = AuthHeader;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).Laythongtin_DMCQTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.LaythongtintaikhoanResponse> GipNcm_V2.CA2_GIPSoap.LaythongtintaikhoanAsync(GipNcm_V2.LaythongtintaikhoanRequest request)
        {
            return base.Channel.LaythongtintaikhoanAsync(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.LaythongtintaikhoanResponse> LaythongtintaikhoanAsync(GipNcm_V2.AuthHeader AuthHeader, string taikhoanin)
        {
            GipNcm_V2.LaythongtintaikhoanRequest inValue = new GipNcm_V2.LaythongtintaikhoanRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.taikhoanin = taikhoanin;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).LaythongtintaikhoanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GipNcm_V2.hash256Response> GipNcm_V2.CA2_GIPSoap.hash256Async(GipNcm_V2.hash256Request request)
        {
            return base.Channel.hash256Async(request);
        }
        
        public System.Threading.Tasks.Task<GipNcm_V2.hash256Response> hash256Async(GipNcm_V2.AuthHeader AuthHeader, string schuoi)
        {
            GipNcm_V2.hash256Request inValue = new GipNcm_V2.hash256Request();
            inValue.AuthHeader = AuthHeader;
            inValue.schuoi = schuoi;
            return ((GipNcm_V2.CA2_GIPSoap)(this)).hash256Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CA2_GIPSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CA2_GIPSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CA2_GIPSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.20.17:26119/CA2_GIP.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CA2_GIPSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.20.17:26119/CA2_GIP.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CA2_GIPSoap,
            
            CA2_GIPSoap12,
        }
    }
}
