'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace servicetvan78uat
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WSInterTRCA2Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WSInterTRCA2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private VerifySignatureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private prLaylogtruyennhan_TvanOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayKhoaphien_MTDiepOperationCompleted As System.Threading.SendOrPostCallback
        
        Private authHeaderValueField As AuthHeader
        
        Private LayKQThongdiep_TCT_UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayKQThongdiep_TCT_TestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayKQThongdiep_TCT_Test1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private GuithongdiepOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayKQThongdiepOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayLogtruyennhan_TCGPOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayLogtruyennhan_TVanOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LaynoidungthongdiepOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Laynoidungthongdiep_chuoixmlOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayKQPhanhoicuathue_ThongbaoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TaoQRCodeHDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Taothongdiepphanhoikythuat_TCTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Boctach_LogfileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XulylogtruyennhanloiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Captaikhoantruyennhan_hsdtOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayketquathongdiepTQ_khoaphienOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LayketquathongdiepTQ_Khoaphien_prefixOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Guithongdiep2024OperationCompleted As System.Threading.SendOrPostCallback
        
        Private Guithongdiep_MTDiepOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WebApplication1.My.MySettings.Default.WebApplication1_servicetvan78uat_WSInterTRCA2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Property AuthHeaderValue() As AuthHeader
            Get
                Return Me.authHeaderValueField
            End Get
            Set
                Me.authHeaderValueField = value
            End Set
        End Property
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event VerifySignatureCompleted As VerifySignatureCompletedEventHandler
        
        '''<remarks/>
        Public Event prLaylogtruyennhan_TvanCompleted As prLaylogtruyennhan_TvanCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKhoaphien_MTDiepCompleted As LayKhoaphien_MTDiepCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKQThongdiep_TCT_UpdateCompleted As LayKQThongdiep_TCT_UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKQThongdiep_TCT_TestCompleted As LayKQThongdiep_TCT_TestCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKQThongdiep_TCT_Test1Completed As LayKQThongdiep_TCT_Test1CompletedEventHandler
        
        '''<remarks/>
        Public Event GuithongdiepCompleted As GuithongdiepCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKQThongdiepCompleted As LayKQThongdiepCompletedEventHandler
        
        '''<remarks/>
        Public Event LayLogtruyennhan_TCGPCompleted As LayLogtruyennhan_TCGPCompletedEventHandler
        
        '''<remarks/>
        Public Event LayLogtruyennhan_TVanCompleted As LayLogtruyennhan_TVanCompletedEventHandler
        
        '''<remarks/>
        Public Event LaynoidungthongdiepCompleted As LaynoidungthongdiepCompletedEventHandler
        
        '''<remarks/>
        Public Event Laynoidungthongdiep_chuoixmlCompleted As Laynoidungthongdiep_chuoixmlCompletedEventHandler
        
        '''<remarks/>
        Public Event LayKQPhanhoicuathue_ThongbaoCompleted As LayKQPhanhoicuathue_ThongbaoCompletedEventHandler
        
        '''<remarks/>
        Public Event TaoQRCodeHDCompleted As TaoQRCodeHDCompletedEventHandler
        
        '''<remarks/>
        Public Event Taothongdiepphanhoikythuat_TCTCompleted As Taothongdiepphanhoikythuat_TCTCompletedEventHandler
        
        '''<remarks/>
        Public Event Boctach_LogfileCompleted As Boctach_LogfileCompletedEventHandler
        
        '''<remarks/>
        Public Event XulylogtruyennhanloiCompleted As XulylogtruyennhanloiCompletedEventHandler
        
        '''<remarks/>
        Public Event CapnhatxulythongdiepkhonglayduockhoaphienCompleted As CapnhatxulythongdiepkhonglayduockhoaphienCompletedEventHandler
        
        '''<remarks/>
        Public Event Captaikhoantruyennhan_hsdtCompleted As Captaikhoantruyennhan_hsdtCompletedEventHandler
        
        '''<remarks/>
        Public Event LayketquathongdiepTQ_khoaphienCompleted As LayketquathongdiepTQ_khoaphienCompletedEventHandler
        
        '''<remarks/>
        Public Event LayketquathongdiepTQ_Khoaphien_prefixCompleted As LayketquathongdiepTQ_Khoaphien_prefixCompletedEventHandler
        
        '''<remarks/>
        Public Event Guithongdiep2024Completed As Guithongdiep2024CompletedEventHandler
        
        '''<remarks/>
        Public Event Guithongdiep_MTDiepCompleted As Guithongdiep_MTDiepCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerifySignature", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerifySignature(ByVal xml As String, ByVal base64 As Integer) As Boolean
            Dim results() As Object = Me.Invoke("VerifySignature", New Object() {xml, base64})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub VerifySignatureAsync(ByVal xml As String, ByVal base64 As Integer)
            Me.VerifySignatureAsync(xml, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub VerifySignatureAsync(ByVal xml As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.VerifySignatureOperationCompleted Is Nothing) Then
                Me.VerifySignatureOperationCompleted = AddressOf Me.OnVerifySignatureOperationCompleted
            End If
            Me.InvokeAsync("VerifySignature", New Object() {xml, base64}, Me.VerifySignatureOperationCompleted, userState)
        End Sub
        
        Private Sub OnVerifySignatureOperationCompleted(ByVal arg As Object)
            If (Not (Me.VerifySignatureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent VerifySignatureCompleted(Me, New VerifySignatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/prLaylogtruyennhan_Tvan", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function prLaylogtruyennhan_Tvan(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("prLaylogtruyennhan_Tvan", New Object() {tungay, denngay, tieuchi})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub prLaylogtruyennhan_TvanAsync(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer)
            Me.prLaylogtruyennhan_TvanAsync(tungay, denngay, tieuchi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub prLaylogtruyennhan_TvanAsync(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer, ByVal userState As Object)
            If (Me.prLaylogtruyennhan_TvanOperationCompleted Is Nothing) Then
                Me.prLaylogtruyennhan_TvanOperationCompleted = AddressOf Me.OnprLaylogtruyennhan_TvanOperationCompleted
            End If
            Me.InvokeAsync("prLaylogtruyennhan_Tvan", New Object() {tungay, denngay, tieuchi}, Me.prLaylogtruyennhan_TvanOperationCompleted, userState)
        End Sub
        
        Private Sub OnprLaylogtruyennhan_TvanOperationCompleted(ByVal arg As Object)
            If (Not (Me.prLaylogtruyennhan_TvanCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent prLaylogtruyennhan_TvanCompleted(Me, New prLaylogtruyennhan_TvanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKhoaphien_MTDiep", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKhoaphien_MTDiep(ByVal MTDiep As String) As String
            Dim results() As Object = Me.Invoke("LayKhoaphien_MTDiep", New Object() {MTDiep})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKhoaphien_MTDiepAsync(ByVal MTDiep As String)
            Me.LayKhoaphien_MTDiepAsync(MTDiep, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKhoaphien_MTDiepAsync(ByVal MTDiep As String, ByVal userState As Object)
            If (Me.LayKhoaphien_MTDiepOperationCompleted Is Nothing) Then
                Me.LayKhoaphien_MTDiepOperationCompleted = AddressOf Me.OnLayKhoaphien_MTDiepOperationCompleted
            End If
            Me.InvokeAsync("LayKhoaphien_MTDiep", New Object() {MTDiep}, Me.LayKhoaphien_MTDiepOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKhoaphien_MTDiepOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKhoaphien_MTDiepCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKhoaphien_MTDiepCompleted(Me, New LayKhoaphien_MTDiepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKQThongdiep_TCT_Update", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKQThongdiep_TCT_Update(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String) As Integer
            Dim results() As Object = Me.Invoke("LayKQThongdiep_TCT_Update", New Object() {xmlthue, base64, idMessage})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_UpdateAsync(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String)
            Me.LayKQThongdiep_TCT_UpdateAsync(xmlthue, base64, idMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_UpdateAsync(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String, ByVal userState As Object)
            If (Me.LayKQThongdiep_TCT_UpdateOperationCompleted Is Nothing) Then
                Me.LayKQThongdiep_TCT_UpdateOperationCompleted = AddressOf Me.OnLayKQThongdiep_TCT_UpdateOperationCompleted
            End If
            Me.InvokeAsync("LayKQThongdiep_TCT_Update", New Object() {xmlthue, base64, idMessage}, Me.LayKQThongdiep_TCT_UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKQThongdiep_TCT_UpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKQThongdiep_TCT_UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKQThongdiep_TCT_UpdateCompleted(Me, New LayKQThongdiep_TCT_UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKQThongdiep_TCT_Test", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKQThongdiep_TCT_Test(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String) As Integer
            Dim results() As Object = Me.Invoke("LayKQThongdiep_TCT_Test", New Object() {xmlthue, base64, idMessage})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_TestAsync(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String)
            Me.LayKQThongdiep_TCT_TestAsync(xmlthue, base64, idMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_TestAsync(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String, ByVal userState As Object)
            If (Me.LayKQThongdiep_TCT_TestOperationCompleted Is Nothing) Then
                Me.LayKQThongdiep_TCT_TestOperationCompleted = AddressOf Me.OnLayKQThongdiep_TCT_TestOperationCompleted
            End If
            Me.InvokeAsync("LayKQThongdiep_TCT_Test", New Object() {xmlthue, base64, idMessage}, Me.LayKQThongdiep_TCT_TestOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKQThongdiep_TCT_TestOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKQThongdiep_TCT_TestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKQThongdiep_TCT_TestCompleted(Me, New LayKQThongdiep_TCT_TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKQThongdiep_TCT_Test1", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKQThongdiep_TCT_Test1(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String) As Integer
            Dim results() As Object = Me.Invoke("LayKQThongdiep_TCT_Test1", New Object() {xmlthue, base64, idMessage})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_Test1Async(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String)
            Me.LayKQThongdiep_TCT_Test1Async(xmlthue, base64, idMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiep_TCT_Test1Async(ByVal xmlthue As String, ByVal base64 As Integer, ByVal idMessage As String, ByVal userState As Object)
            If (Me.LayKQThongdiep_TCT_Test1OperationCompleted Is Nothing) Then
                Me.LayKQThongdiep_TCT_Test1OperationCompleted = AddressOf Me.OnLayKQThongdiep_TCT_Test1OperationCompleted
            End If
            Me.InvokeAsync("LayKQThongdiep_TCT_Test1", New Object() {xmlthue, base64, idMessage}, Me.LayKQThongdiep_TCT_Test1OperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKQThongdiep_TCT_Test1OperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKQThongdiep_TCT_Test1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKQThongdiep_TCT_Test1Completed(Me, New LayKQThongdiep_TCT_Test1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guithongdiep", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Guithongdiep(ByVal Noidungthongdiep As String, ByVal base64 As Integer) As String
            Dim results() As Object = Me.Invoke("Guithongdiep", New Object() {Noidungthongdiep, base64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GuithongdiepAsync(ByVal Noidungthongdiep As String, ByVal base64 As Integer)
            Me.GuithongdiepAsync(Noidungthongdiep, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GuithongdiepAsync(ByVal Noidungthongdiep As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.GuithongdiepOperationCompleted Is Nothing) Then
                Me.GuithongdiepOperationCompleted = AddressOf Me.OnGuithongdiepOperationCompleted
            End If
            Me.InvokeAsync("Guithongdiep", New Object() {Noidungthongdiep, base64}, Me.GuithongdiepOperationCompleted, userState)
        End Sub
        
        Private Sub OnGuithongdiepOperationCompleted(ByVal arg As Object)
            If (Not (Me.GuithongdiepCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GuithongdiepCompleted(Me, New GuithongdiepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKQThongdiep", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKQThongdiep(ByVal Khoaphien As String, ByVal MST As String) As String
            Dim results() As Object = Me.Invoke("LayKQThongdiep", New Object() {Khoaphien, MST})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiepAsync(ByVal Khoaphien As String, ByVal MST As String)
            Me.LayKQThongdiepAsync(Khoaphien, MST, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKQThongdiepAsync(ByVal Khoaphien As String, ByVal MST As String, ByVal userState As Object)
            If (Me.LayKQThongdiepOperationCompleted Is Nothing) Then
                Me.LayKQThongdiepOperationCompleted = AddressOf Me.OnLayKQThongdiepOperationCompleted
            End If
            Me.InvokeAsync("LayKQThongdiep", New Object() {Khoaphien, MST}, Me.LayKQThongdiepOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKQThongdiepOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKQThongdiepCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKQThongdiepCompleted(Me, New LayKQThongdiepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayLogtruyennhan_TCGP", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayLogtruyennhan_TCGP(ByVal MST As String, ByVal tungay As String, ByVal denngay As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("LayLogtruyennhan_TCGP", New Object() {MST, tungay, denngay})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayLogtruyennhan_TCGPAsync(ByVal MST As String, ByVal tungay As String, ByVal denngay As String)
            Me.LayLogtruyennhan_TCGPAsync(MST, tungay, denngay, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayLogtruyennhan_TCGPAsync(ByVal MST As String, ByVal tungay As String, ByVal denngay As String, ByVal userState As Object)
            If (Me.LayLogtruyennhan_TCGPOperationCompleted Is Nothing) Then
                Me.LayLogtruyennhan_TCGPOperationCompleted = AddressOf Me.OnLayLogtruyennhan_TCGPOperationCompleted
            End If
            Me.InvokeAsync("LayLogtruyennhan_TCGP", New Object() {MST, tungay, denngay}, Me.LayLogtruyennhan_TCGPOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayLogtruyennhan_TCGPOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayLogtruyennhan_TCGPCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayLogtruyennhan_TCGPCompleted(Me, New LayLogtruyennhan_TCGPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayLogtruyennhan_TVan", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayLogtruyennhan_TVan(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer, ByVal MST As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("LayLogtruyennhan_TVan", New Object() {tungay, denngay, tieuchi, MST})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayLogtruyennhan_TVanAsync(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer, ByVal MST As String)
            Me.LayLogtruyennhan_TVanAsync(tungay, denngay, tieuchi, MST, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayLogtruyennhan_TVanAsync(ByVal tungay As String, ByVal denngay As String, ByVal tieuchi As Integer, ByVal MST As String, ByVal userState As Object)
            If (Me.LayLogtruyennhan_TVanOperationCompleted Is Nothing) Then
                Me.LayLogtruyennhan_TVanOperationCompleted = AddressOf Me.OnLayLogtruyennhan_TVanOperationCompleted
            End If
            Me.InvokeAsync("LayLogtruyennhan_TVan", New Object() {tungay, denngay, tieuchi, MST}, Me.LayLogtruyennhan_TVanOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayLogtruyennhan_TVanOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayLogtruyennhan_TVanCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayLogtruyennhan_TVanCompleted(Me, New LayLogtruyennhan_TVanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Laynoidungthongdiep", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Laynoidungthongdiep(ByVal base64xml As String) As Thongdiep
            Dim results() As Object = Me.Invoke("Laynoidungthongdiep", New Object() {base64xml})
            Return CType(results(0),Thongdiep)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LaynoidungthongdiepAsync(ByVal base64xml As String)
            Me.LaynoidungthongdiepAsync(base64xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LaynoidungthongdiepAsync(ByVal base64xml As String, ByVal userState As Object)
            If (Me.LaynoidungthongdiepOperationCompleted Is Nothing) Then
                Me.LaynoidungthongdiepOperationCompleted = AddressOf Me.OnLaynoidungthongdiepOperationCompleted
            End If
            Me.InvokeAsync("Laynoidungthongdiep", New Object() {base64xml}, Me.LaynoidungthongdiepOperationCompleted, userState)
        End Sub
        
        Private Sub OnLaynoidungthongdiepOperationCompleted(ByVal arg As Object)
            If (Not (Me.LaynoidungthongdiepCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LaynoidungthongdiepCompleted(Me, New LaynoidungthongdiepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Laynoidungthongdiep_chuoixml", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Laynoidungthongdiep_chuoixml(ByVal chuoixml As String) As Thongdiep
            Dim results() As Object = Me.Invoke("Laynoidungthongdiep_chuoixml", New Object() {chuoixml})
            Return CType(results(0),Thongdiep)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Laynoidungthongdiep_chuoixmlAsync(ByVal chuoixml As String)
            Me.Laynoidungthongdiep_chuoixmlAsync(chuoixml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Laynoidungthongdiep_chuoixmlAsync(ByVal chuoixml As String, ByVal userState As Object)
            If (Me.Laynoidungthongdiep_chuoixmlOperationCompleted Is Nothing) Then
                Me.Laynoidungthongdiep_chuoixmlOperationCompleted = AddressOf Me.OnLaynoidungthongdiep_chuoixmlOperationCompleted
            End If
            Me.InvokeAsync("Laynoidungthongdiep_chuoixml", New Object() {chuoixml}, Me.Laynoidungthongdiep_chuoixmlOperationCompleted, userState)
        End Sub
        
        Private Sub OnLaynoidungthongdiep_chuoixmlOperationCompleted(ByVal arg As Object)
            If (Not (Me.Laynoidungthongdiep_chuoixmlCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Laynoidungthongdiep_chuoixmlCompleted(Me, New Laynoidungthongdiep_chuoixmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayKQPhanhoicuathue_Thongbao", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayKQPhanhoicuathue_Thongbao(ByVal chuoixml As String, ByVal base64 As Integer) As String
            Dim results() As Object = Me.Invoke("LayKQPhanhoicuathue_Thongbao", New Object() {chuoixml, base64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayKQPhanhoicuathue_ThongbaoAsync(ByVal chuoixml As String, ByVal base64 As Integer)
            Me.LayKQPhanhoicuathue_ThongbaoAsync(chuoixml, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayKQPhanhoicuathue_ThongbaoAsync(ByVal chuoixml As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.LayKQPhanhoicuathue_ThongbaoOperationCompleted Is Nothing) Then
                Me.LayKQPhanhoicuathue_ThongbaoOperationCompleted = AddressOf Me.OnLayKQPhanhoicuathue_ThongbaoOperationCompleted
            End If
            Me.InvokeAsync("LayKQPhanhoicuathue_Thongbao", New Object() {chuoixml, base64}, Me.LayKQPhanhoicuathue_ThongbaoOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayKQPhanhoicuathue_ThongbaoOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayKQPhanhoicuathue_ThongbaoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayKQPhanhoicuathue_ThongbaoCompleted(Me, New LayKQPhanhoicuathue_ThongbaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TaoQRCodeHD", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TaoQRCodeHD(ByVal MSTNguoiban As String, ByVal KHMSHDon As String, ByVal KHHDon As String, ByVal SHDon As String, ByVal NLap As String, ByVal Tongtienthanhtoan As String) As String
            Dim results() As Object = Me.Invoke("TaoQRCodeHD", New Object() {MSTNguoiban, KHMSHDon, KHHDon, SHDon, NLap, Tongtienthanhtoan})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TaoQRCodeHDAsync(ByVal MSTNguoiban As String, ByVal KHMSHDon As String, ByVal KHHDon As String, ByVal SHDon As String, ByVal NLap As String, ByVal Tongtienthanhtoan As String)
            Me.TaoQRCodeHDAsync(MSTNguoiban, KHMSHDon, KHHDon, SHDon, NLap, Tongtienthanhtoan, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TaoQRCodeHDAsync(ByVal MSTNguoiban As String, ByVal KHMSHDon As String, ByVal KHHDon As String, ByVal SHDon As String, ByVal NLap As String, ByVal Tongtienthanhtoan As String, ByVal userState As Object)
            If (Me.TaoQRCodeHDOperationCompleted Is Nothing) Then
                Me.TaoQRCodeHDOperationCompleted = AddressOf Me.OnTaoQRCodeHDOperationCompleted
            End If
            Me.InvokeAsync("TaoQRCodeHD", New Object() {MSTNguoiban, KHMSHDon, KHHDon, SHDon, NLap, Tongtienthanhtoan}, Me.TaoQRCodeHDOperationCompleted, userState)
        End Sub
        
        Private Sub OnTaoQRCodeHDOperationCompleted(ByVal arg As Object)
            If (Not (Me.TaoQRCodeHDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TaoQRCodeHDCompleted(Me, New TaoQRCodeHDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Taothongdiepphanhoikythuat_TCT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Taothongdiepphanhoikythuat_TCT(ByVal ThongdiepTCT As String, ByVal TTTNhanDL As String, ByVal base64 As Integer) As String
            Dim results() As Object = Me.Invoke("Taothongdiepphanhoikythuat_TCT", New Object() {ThongdiepTCT, TTTNhanDL, base64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Taothongdiepphanhoikythuat_TCTAsync(ByVal ThongdiepTCT As String, ByVal TTTNhanDL As String, ByVal base64 As Integer)
            Me.Taothongdiepphanhoikythuat_TCTAsync(ThongdiepTCT, TTTNhanDL, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Taothongdiepphanhoikythuat_TCTAsync(ByVal ThongdiepTCT As String, ByVal TTTNhanDL As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.Taothongdiepphanhoikythuat_TCTOperationCompleted Is Nothing) Then
                Me.Taothongdiepphanhoikythuat_TCTOperationCompleted = AddressOf Me.OnTaothongdiepphanhoikythuat_TCTOperationCompleted
            End If
            Me.InvokeAsync("Taothongdiepphanhoikythuat_TCT", New Object() {ThongdiepTCT, TTTNhanDL, base64}, Me.Taothongdiepphanhoikythuat_TCTOperationCompleted, userState)
        End Sub
        
        Private Sub OnTaothongdiepphanhoikythuat_TCTOperationCompleted(ByVal arg As Object)
            If (Not (Me.Taothongdiepphanhoikythuat_TCTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Taothongdiepphanhoikythuat_TCTCompleted(Me, New Taothongdiepphanhoikythuat_TCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Boctach_Logfile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Boctach_Logfile(ByVal tungay As String, ByVal denngay As String) As Integer
            Dim results() As Object = Me.Invoke("Boctach_Logfile", New Object() {tungay, denngay})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Boctach_LogfileAsync(ByVal tungay As String, ByVal denngay As String)
            Me.Boctach_LogfileAsync(tungay, denngay, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Boctach_LogfileAsync(ByVal tungay As String, ByVal denngay As String, ByVal userState As Object)
            If (Me.Boctach_LogfileOperationCompleted Is Nothing) Then
                Me.Boctach_LogfileOperationCompleted = AddressOf Me.OnBoctach_LogfileOperationCompleted
            End If
            Me.InvokeAsync("Boctach_Logfile", New Object() {tungay, denngay}, Me.Boctach_LogfileOperationCompleted, userState)
        End Sub
        
        Private Sub OnBoctach_LogfileOperationCompleted(ByVal arg As Object)
            If (Not (Me.Boctach_LogfileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Boctach_LogfileCompleted(Me, New Boctach_LogfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Xulylogtruyennhanloi", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Xulylogtruyennhanloi(ByVal tungay As String, ByVal denngay As String) As Integer
            Dim results() As Object = Me.Invoke("Xulylogtruyennhanloi", New Object() {tungay, denngay})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XulylogtruyennhanloiAsync(ByVal tungay As String, ByVal denngay As String)
            Me.XulylogtruyennhanloiAsync(tungay, denngay, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XulylogtruyennhanloiAsync(ByVal tungay As String, ByVal denngay As String, ByVal userState As Object)
            If (Me.XulylogtruyennhanloiOperationCompleted Is Nothing) Then
                Me.XulylogtruyennhanloiOperationCompleted = AddressOf Me.OnXulylogtruyennhanloiOperationCompleted
            End If
            Me.InvokeAsync("Xulylogtruyennhanloi", New Object() {tungay, denngay}, Me.XulylogtruyennhanloiOperationCompleted, userState)
        End Sub
        
        Private Sub OnXulylogtruyennhanloiOperationCompleted(ByVal arg As Object)
            If (Not (Me.XulylogtruyennhanloiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XulylogtruyennhanloiCompleted(Me, New XulylogtruyennhanloiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Capnhatxulythongdiepkhonglayduockhoaphien", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Capnhatxulythongdiepkhonglayduockhoaphien() As Integer
            Dim results() As Object = Me.Invoke("Capnhatxulythongdiepkhonglayduockhoaphien", New Object(-1) {})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub CapnhatxulythongdiepkhonglayduockhoaphienAsync()
            Me.CapnhatxulythongdiepkhonglayduockhoaphienAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CapnhatxulythongdiepkhonglayduockhoaphienAsync(ByVal userState As Object)
            If (Me.CapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted Is Nothing) Then
                Me.CapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted = AddressOf Me.OnCapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted
            End If
            Me.InvokeAsync("Capnhatxulythongdiepkhonglayduockhoaphien", New Object(-1) {}, Me.CapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted, userState)
        End Sub
        
        Private Sub OnCapnhatxulythongdiepkhonglayduockhoaphienOperationCompleted(ByVal arg As Object)
            If (Not (Me.CapnhatxulythongdiepkhonglayduockhoaphienCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CapnhatxulythongdiepkhonglayduockhoaphienCompleted(Me, New CapnhatxulythongdiepkhonglayduockhoaphienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Captaikhoantruyennhan_hsdt", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Captaikhoantruyennhan_hsdt(ByVal Masothue As String, ByVal MaGoi As String, ByVal idHSDT As Integer, ByVal Taikhoan_HSDT As String) As String
            Dim results() As Object = Me.Invoke("Captaikhoantruyennhan_hsdt", New Object() {Masothue, MaGoi, idHSDT, Taikhoan_HSDT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Captaikhoantruyennhan_hsdtAsync(ByVal Masothue As String, ByVal MaGoi As String, ByVal idHSDT As Integer, ByVal Taikhoan_HSDT As String)
            Me.Captaikhoantruyennhan_hsdtAsync(Masothue, MaGoi, idHSDT, Taikhoan_HSDT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Captaikhoantruyennhan_hsdtAsync(ByVal Masothue As String, ByVal MaGoi As String, ByVal idHSDT As Integer, ByVal Taikhoan_HSDT As String, ByVal userState As Object)
            If (Me.Captaikhoantruyennhan_hsdtOperationCompleted Is Nothing) Then
                Me.Captaikhoantruyennhan_hsdtOperationCompleted = AddressOf Me.OnCaptaikhoantruyennhan_hsdtOperationCompleted
            End If
            Me.InvokeAsync("Captaikhoantruyennhan_hsdt", New Object() {Masothue, MaGoi, idHSDT, Taikhoan_HSDT}, Me.Captaikhoantruyennhan_hsdtOperationCompleted, userState)
        End Sub
        
        Private Sub OnCaptaikhoantruyennhan_hsdtOperationCompleted(ByVal arg As Object)
            If (Not (Me.Captaikhoantruyennhan_hsdtCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Captaikhoantruyennhan_hsdtCompleted(Me, New Captaikhoantruyennhan_hsdtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayketquathongdiepTQ_khoaphien", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayketquathongdiepTQ_khoaphien(ByVal Khoaphien As String, ByVal MSTTCGP As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("LayketquathongdiepTQ_khoaphien", New Object() {Khoaphien, MSTTCGP})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayketquathongdiepTQ_khoaphienAsync(ByVal Khoaphien As String, ByVal MSTTCGP As String)
            Me.LayketquathongdiepTQ_khoaphienAsync(Khoaphien, MSTTCGP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayketquathongdiepTQ_khoaphienAsync(ByVal Khoaphien As String, ByVal MSTTCGP As String, ByVal userState As Object)
            If (Me.LayketquathongdiepTQ_khoaphienOperationCompleted Is Nothing) Then
                Me.LayketquathongdiepTQ_khoaphienOperationCompleted = AddressOf Me.OnLayketquathongdiepTQ_khoaphienOperationCompleted
            End If
            Me.InvokeAsync("LayketquathongdiepTQ_khoaphien", New Object() {Khoaphien, MSTTCGP}, Me.LayketquathongdiepTQ_khoaphienOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayketquathongdiepTQ_khoaphienOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayketquathongdiepTQ_khoaphienCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayketquathongdiepTQ_khoaphienCompleted(Me, New LayketquathongdiepTQ_khoaphienCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayketquathongdiepTQ_Khoaphien_prefix", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LayketquathongdiepTQ_Khoaphien_prefix(ByVal Khoaphien_prefix As String, ByVal MSTTCGP As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("LayketquathongdiepTQ_Khoaphien_prefix", New Object() {Khoaphien_prefix, MSTTCGP})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LayketquathongdiepTQ_Khoaphien_prefixAsync(ByVal Khoaphien_prefix As String, ByVal MSTTCGP As String)
            Me.LayketquathongdiepTQ_Khoaphien_prefixAsync(Khoaphien_prefix, MSTTCGP, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LayketquathongdiepTQ_Khoaphien_prefixAsync(ByVal Khoaphien_prefix As String, ByVal MSTTCGP As String, ByVal userState As Object)
            If (Me.LayketquathongdiepTQ_Khoaphien_prefixOperationCompleted Is Nothing) Then
                Me.LayketquathongdiepTQ_Khoaphien_prefixOperationCompleted = AddressOf Me.OnLayketquathongdiepTQ_Khoaphien_prefixOperationCompleted
            End If
            Me.InvokeAsync("LayketquathongdiepTQ_Khoaphien_prefix", New Object() {Khoaphien_prefix, MSTTCGP}, Me.LayketquathongdiepTQ_Khoaphien_prefixOperationCompleted, userState)
        End Sub
        
        Private Sub OnLayketquathongdiepTQ_Khoaphien_prefixOperationCompleted(ByVal arg As Object)
            If (Not (Me.LayketquathongdiepTQ_Khoaphien_prefixCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LayketquathongdiepTQ_Khoaphien_prefixCompleted(Me, New LayketquathongdiepTQ_Khoaphien_prefixCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guithongdiep2024", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Guithongdiep2024(ByVal Noidungthongdiep As String, ByVal base64 As Integer) As String
            Dim results() As Object = Me.Invoke("Guithongdiep2024", New Object() {Noidungthongdiep, base64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Guithongdiep2024Async(ByVal Noidungthongdiep As String, ByVal base64 As Integer)
            Me.Guithongdiep2024Async(Noidungthongdiep, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Guithongdiep2024Async(ByVal Noidungthongdiep As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.Guithongdiep2024OperationCompleted Is Nothing) Then
                Me.Guithongdiep2024OperationCompleted = AddressOf Me.OnGuithongdiep2024OperationCompleted
            End If
            Me.InvokeAsync("Guithongdiep2024", New Object() {Noidungthongdiep, base64}, Me.Guithongdiep2024OperationCompleted, userState)
        End Sub
        
        Private Sub OnGuithongdiep2024OperationCompleted(ByVal arg As Object)
            If (Not (Me.Guithongdiep2024CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Guithongdiep2024Completed(Me, New Guithongdiep2024CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Guithongdiep_MTDiep", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Guithongdiep_MTDiep(ByVal Noidungthongdiep As String, ByVal base64 As Integer) As String
            Dim results() As Object = Me.Invoke("Guithongdiep_MTDiep", New Object() {Noidungthongdiep, base64})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Guithongdiep_MTDiepAsync(ByVal Noidungthongdiep As String, ByVal base64 As Integer)
            Me.Guithongdiep_MTDiepAsync(Noidungthongdiep, base64, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Guithongdiep_MTDiepAsync(ByVal Noidungthongdiep As String, ByVal base64 As Integer, ByVal userState As Object)
            If (Me.Guithongdiep_MTDiepOperationCompleted Is Nothing) Then
                Me.Guithongdiep_MTDiepOperationCompleted = AddressOf Me.OnGuithongdiep_MTDiepOperationCompleted
            End If
            Me.InvokeAsync("Guithongdiep_MTDiep", New Object() {Noidungthongdiep, base64}, Me.Guithongdiep_MTDiepOperationCompleted, userState)
        End Sub
        
        Private Sub OnGuithongdiep_MTDiepOperationCompleted(ByVal arg As Object)
            If (Not (Me.Guithongdiep_MTDiepCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Guithongdiep_MTDiepCompleted(Me, New Guithongdiep_MTDiepCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://tempuri.org/", IsNullable:=false)>  _
    Partial Public Class AuthHeader
        Inherits System.Web.Services.Protocols.SoapHeader
        
        Private usernameField As String
        
        Private passwordField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        Public Property Username() As String
            Get
                Return Me.usernameField
            End Get
            Set
                Me.usernameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Thongdiep
        
        Private pBanField As String
        
        Private mNGuiField As String
        
        Private mNNhanField As String
        
        Private mLTDiepField As String
        
        Private mTDiepField As String
        
        Private mTDTChieuField As String
        
        Private mSTField As String
        
        Private sLuongField As String
        
        Private dLieuField As String
        
        Private id_DLieuField As String
        
        Private cKSNNTField As String
        
        Private checkDLField As Integer
        
        '''<remarks/>
        Public Property PBan() As String
            Get
                Return Me.pBanField
            End Get
            Set
                Me.pBanField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MNGui() As String
            Get
                Return Me.mNGuiField
            End Get
            Set
                Me.mNGuiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MNNhan() As String
            Get
                Return Me.mNNhanField
            End Get
            Set
                Me.mNNhanField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MLTDiep() As String
            Get
                Return Me.mLTDiepField
            End Get
            Set
                Me.mLTDiepField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MTDiep() As String
            Get
                Return Me.mTDiepField
            End Get
            Set
                Me.mTDiepField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MTDTChieu() As String
            Get
                Return Me.mTDTChieuField
            End Get
            Set
                Me.mTDTChieuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MST() As String
            Get
                Return Me.mSTField
            End Get
            Set
                Me.mSTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SLuong() As String
            Get
                Return Me.sLuongField
            End Get
            Set
                Me.sLuongField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DLieu() As String
            Get
                Return Me.dLieuField
            End Get
            Set
                Me.dLieuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Id_DLieu() As String
            Get
                Return Me.id_DLieuField
            End Get
            Set
                Me.id_DLieuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CKSNNT() As String
            Get
                Return Me.cKSNNTField
            End Get
            Set
                Me.cKSNNTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CheckDL() As Integer
            Get
                Return Me.checkDLField
            End Get
            Set
                Me.checkDLField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub VerifySignatureCompletedEventHandler(ByVal sender As Object, ByVal e As VerifySignatureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class VerifySignatureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub prLaylogtruyennhan_TvanCompletedEventHandler(ByVal sender As Object, ByVal e As prLaylogtruyennhan_TvanCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class prLaylogtruyennhan_TvanCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKhoaphien_MTDiepCompletedEventHandler(ByVal sender As Object, ByVal e As LayKhoaphien_MTDiepCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKhoaphien_MTDiepCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKQThongdiep_TCT_UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As LayKQThongdiep_TCT_UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKQThongdiep_TCT_UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKQThongdiep_TCT_TestCompletedEventHandler(ByVal sender As Object, ByVal e As LayKQThongdiep_TCT_TestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKQThongdiep_TCT_TestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKQThongdiep_TCT_Test1CompletedEventHandler(ByVal sender As Object, ByVal e As LayKQThongdiep_TCT_Test1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKQThongdiep_TCT_Test1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GuithongdiepCompletedEventHandler(ByVal sender As Object, ByVal e As GuithongdiepCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GuithongdiepCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKQThongdiepCompletedEventHandler(ByVal sender As Object, ByVal e As LayKQThongdiepCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKQThongdiepCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayLogtruyennhan_TCGPCompletedEventHandler(ByVal sender As Object, ByVal e As LayLogtruyennhan_TCGPCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayLogtruyennhan_TCGPCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayLogtruyennhan_TVanCompletedEventHandler(ByVal sender As Object, ByVal e As LayLogtruyennhan_TVanCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayLogtruyennhan_TVanCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LaynoidungthongdiepCompletedEventHandler(ByVal sender As Object, ByVal e As LaynoidungthongdiepCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LaynoidungthongdiepCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Thongdiep
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Thongdiep)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Laynoidungthongdiep_chuoixmlCompletedEventHandler(ByVal sender As Object, ByVal e As Laynoidungthongdiep_chuoixmlCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Laynoidungthongdiep_chuoixmlCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Thongdiep
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Thongdiep)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayKQPhanhoicuathue_ThongbaoCompletedEventHandler(ByVal sender As Object, ByVal e As LayKQPhanhoicuathue_ThongbaoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayKQPhanhoicuathue_ThongbaoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TaoQRCodeHDCompletedEventHandler(ByVal sender As Object, ByVal e As TaoQRCodeHDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TaoQRCodeHDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Taothongdiepphanhoikythuat_TCTCompletedEventHandler(ByVal sender As Object, ByVal e As Taothongdiepphanhoikythuat_TCTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Taothongdiepphanhoikythuat_TCTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Boctach_LogfileCompletedEventHandler(ByVal sender As Object, ByVal e As Boctach_LogfileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Boctach_LogfileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XulylogtruyennhanloiCompletedEventHandler(ByVal sender As Object, ByVal e As XulylogtruyennhanloiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XulylogtruyennhanloiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub CapnhatxulythongdiepkhonglayduockhoaphienCompletedEventHandler(ByVal sender As Object, ByVal e As CapnhatxulythongdiepkhonglayduockhoaphienCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CapnhatxulythongdiepkhonglayduockhoaphienCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Captaikhoantruyennhan_hsdtCompletedEventHandler(ByVal sender As Object, ByVal e As Captaikhoantruyennhan_hsdtCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Captaikhoantruyennhan_hsdtCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayketquathongdiepTQ_khoaphienCompletedEventHandler(ByVal sender As Object, ByVal e As LayketquathongdiepTQ_khoaphienCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayketquathongdiepTQ_khoaphienCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LayketquathongdiepTQ_Khoaphien_prefixCompletedEventHandler(ByVal sender As Object, ByVal e As LayketquathongdiepTQ_Khoaphien_prefixCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LayketquathongdiepTQ_Khoaphien_prefixCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Guithongdiep2024CompletedEventHandler(ByVal sender As Object, ByVal e As Guithongdiep2024CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Guithongdiep2024CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub Guithongdiep_MTDiepCompletedEventHandler(ByVal sender As Object, ByVal e As Guithongdiep_MTDiepCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Guithongdiep_MTDiepCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
