<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\Contract.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.106.21" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.103.51" />
    <PackageReference Include="ExcelDataReader" Version="3.6.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.0.2" />
    <PackageReference Include="Polly" Version="8.6.4" />
    <PackageReference Include="PuppeteerSharp" Version="18.1.0" />
    <PackageReference Include="RabbitMQ.Client" Version="6.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.17" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.2" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.Federation" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.*" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Core\" />
    <None Remove="User\" />
    <None Remove="Category\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="User\" />
    <Folder Include="Category\" />
  </ItemGroup>
</Project>
