<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:tns="http://tempuri.org/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="GetResp_Kafka">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="matd" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="thoigian" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetResp_KafkaResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetResp_KafkaResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="BoctachXML_TCT_UpdateLGG">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="xmlThongdiep" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="BoctachXML_TCT_UpdateLGGResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="BoctachXML_TCT_UpdateLGGResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="string" nillable="true" type="s:string" />
    </s:schema>
  </wsdl:types>
  <wsdl:message name="GetResp_KafkaSoapIn">
    <wsdl:part name="parameters" element="tns:GetResp_Kafka" />
  </wsdl:message>
  <wsdl:message name="GetResp_KafkaSoapOut">
    <wsdl:part name="parameters" element="tns:GetResp_KafkaResponse" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGSoapIn">
    <wsdl:part name="parameters" element="tns:BoctachXML_TCT_UpdateLGG" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGSoapOut">
    <wsdl:part name="parameters" element="tns:BoctachXML_TCT_UpdateLGGResponse" />
  </wsdl:message>
  <wsdl:message name="GetResp_KafkaHttpGetIn">
    <wsdl:part name="matd" type="s:string" />
    <wsdl:part name="thoigian" type="s:string" />
  </wsdl:message>
  <wsdl:message name="GetResp_KafkaHttpGetOut">
    <wsdl:part name="Body" element="tns:string" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGHttpGetIn">
    <wsdl:part name="xmlThongdiep" type="s:string" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGHttpGetOut">
    <wsdl:part name="Body" element="tns:string" />
  </wsdl:message>
  <wsdl:message name="GetResp_KafkaHttpPostIn">
    <wsdl:part name="matd" type="s:string" />
    <wsdl:part name="thoigian" type="s:string" />
  </wsdl:message>
  <wsdl:message name="GetResp_KafkaHttpPostOut">
    <wsdl:part name="Body" element="tns:string" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGHttpPostIn">
    <wsdl:part name="xmlThongdiep" type="s:string" />
  </wsdl:message>
  <wsdl:message name="BoctachXML_TCT_UpdateLGGHttpPostOut">
    <wsdl:part name="Body" element="tns:string" />
  </wsdl:message>
  <wsdl:portType name="ResponseKafkaSoap">
    <wsdl:operation name="GetResp_Kafka">
      <wsdl:input message="tns:GetResp_KafkaSoapIn" />
      <wsdl:output message="tns:GetResp_KafkaSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <wsdl:input message="tns:BoctachXML_TCT_UpdateLGGSoapIn" />
      <wsdl:output message="tns:BoctachXML_TCT_UpdateLGGSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:portType name="ResponseKafkaHttpGet">
    <wsdl:operation name="GetResp_Kafka">
      <wsdl:input message="tns:GetResp_KafkaHttpGetIn" />
      <wsdl:output message="tns:GetResp_KafkaHttpGetOut" />
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <wsdl:input message="tns:BoctachXML_TCT_UpdateLGGHttpGetIn" />
      <wsdl:output message="tns:BoctachXML_TCT_UpdateLGGHttpGetOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:portType name="ResponseKafkaHttpPost">
    <wsdl:operation name="GetResp_Kafka">
      <wsdl:input message="tns:GetResp_KafkaHttpPostIn" />
      <wsdl:output message="tns:GetResp_KafkaHttpPostOut" />
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <wsdl:input message="tns:BoctachXML_TCT_UpdateLGGHttpPostIn" />
      <wsdl:output message="tns:BoctachXML_TCT_UpdateLGGHttpPostOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ResponseKafkaSoap" type="tns:ResponseKafkaSoap">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetResp_Kafka">
      <soap:operation soapAction="http://tempuri.org/GetResp_Kafka" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <soap:operation soapAction="http://tempuri.org/BoctachXML_TCT_UpdateLGG" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ResponseKafkaSoap12" type="tns:ResponseKafkaSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="GetResp_Kafka">
      <soap12:operation soapAction="http://tempuri.org/GetResp_Kafka" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <soap12:operation soapAction="http://tempuri.org/BoctachXML_TCT_UpdateLGG" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ResponseKafkaHttpGet" type="tns:ResponseKafkaHttpGet">
    <http:binding verb="GET" />
    <wsdl:operation name="GetResp_Kafka">
      <http:operation location="/GetResp_Kafka" />
      <wsdl:input>
        <http:urlEncoded />
      </wsdl:input>
      <wsdl:output>
        <mime:mimeXml part="Body" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <http:operation location="/BoctachXML_TCT_UpdateLGG" />
      <wsdl:input>
        <http:urlEncoded />
      </wsdl:input>
      <wsdl:output>
        <mime:mimeXml part="Body" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="ResponseKafkaHttpPost" type="tns:ResponseKafkaHttpPost">
    <http:binding verb="POST" />
    <wsdl:operation name="GetResp_Kafka">
      <http:operation location="/GetResp_Kafka" />
      <wsdl:input>
        <mime:content type="application/x-www-form-urlencoded" />
      </wsdl:input>
      <wsdl:output>
        <mime:mimeXml part="Body" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="BoctachXML_TCT_UpdateLGG">
      <http:operation location="/BoctachXML_TCT_UpdateLGG" />
      <wsdl:input>
        <mime:content type="application/x-www-form-urlencoded" />
      </wsdl:input>
      <wsdl:output>
        <mime:mimeXml part="Body" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ResponseKafka">
    <wsdl:port name="ResponseKafkaSoap" binding="tns:ResponseKafkaSoap">
      <soap:address location="https://kafka.nacencomm.vn/ResponseKafka.asmx" />
    </wsdl:port>
    <wsdl:port name="ResponseKafkaSoap12" binding="tns:ResponseKafkaSoap12">
      <soap12:address location="https://kafka.nacencomm.vn/ResponseKafka.asmx" />
    </wsdl:port>
    <wsdl:port name="ResponseKafkaHttpGet" binding="tns:ResponseKafkaHttpGet">
      <http:address location="https://kafka.nacencomm.vn/ResponseKafka.asmx" />
    </wsdl:port>
    <wsdl:port name="ResponseKafkaHttpPost" binding="tns:ResponseKafkaHttpPost">
      <http:address location="https://kafka.nacencomm.vn/ResponseKafka.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>