//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSInterTRCA2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSInterTRCA2.WSInterTRCA2Soap")]
    public interface WSInterTRCA2Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifySignature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> VerifySignatureAsync(string xml, int base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKhoaphien_MTDiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LayKhoaphien_MTDiepAsync(string MTDiep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQThongdiep_TCT_Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_UpdateResponse> LayKQThongdiep_TCT_UpdateAsync(WSInterTRCA2.LayKQThongdiep_TCT_UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQThongdiep_TCT_Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_TestResponse> LayKQThongdiep_TCT_TestAsync(WSInterTRCA2.LayKQThongdiep_TCT_TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQThongdiep_TCT_Test_new", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Test_newResponse> LayKQThongdiep_TCT_Test_newAsync(WSInterTRCA2.LayKQThongdiep_TCT_Test_newRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guithongdiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.GuithongdiepResponse> GuithongdiepAsync(WSInterTRCA2.GuithongdiepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQThongdiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiepResponse> LayKQThongdiepAsync(WSInterTRCA2.LayKQThongdiepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayLogtruyennhan_TCGP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TCGPResponse> LayLogtruyennhan_TCGPAsync(WSInterTRCA2.LayLogtruyennhan_TCGPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayLogtruyennhan_TVan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TVanResponse> LayLogtruyennhan_TVanAsync(WSInterTRCA2.LayLogtruyennhan_TVanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laynoidungthongdiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.Thongdiep> LaynoidungthongdiepAsync(string base64xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Laynoidungthongdiep_chuoixml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.Thongdiep> Laynoidungthongdiep_chuoixmlAsync(string chuoixml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQPhanhoicuathue_Thongbao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> LayKQPhanhoicuathue_ThongbaoAsync(string chuoixml, int base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TaoQRCodeHD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TaoQRCodeHDAsync(string MSTNguoiban, string KHMSHDon, string KHHDon, string SHDon, string NLap, string Tongtienthanhtoan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Taothongdiepphanhoikythuat_TCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> Taothongdiepphanhoikythuat_TCTAsync(string ThongdiepTCT, string TTTNhanDL, int base64);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Layphanhoi206_khoaphien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.Layphanhoi206_khoaphienResponse> Layphanhoi206_khoaphienAsync(WSInterTRCA2.Layphanhoi206_khoaphienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayketquathongdiepTQ_khoaphien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_khoaphienResponse> LayketquathongdiepTQ_khoaphienAsync(WSInterTRCA2.LayketquathongdiepTQ_khoaphienRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayketquathongdiepTQ_Khoaphien_prefix", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixResponse> LayketquathongdiepTQ_Khoaphien_prefixAsync(WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQThongdiep_TCT_Update_2024", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Response> LayKQThongdiep_TCT_Update_2024Async(WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guithongdiep_MTDiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep_MTDiepResponse> Guithongdiep_MTDiepAsync(WSInterTRCA2.Guithongdiep_MTDiepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guithongdiep2024", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep2024Response> Guithongdiep2024Async(WSInterTRCA2.Guithongdiep2024Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LayKQTruyennhantokhaichungtu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQTruyennhantokhaichungtuResponseLayKQTruyennhantokhaichungtuResult> LayKQTruyennhantokhaichungtuAsync(string MaDV, string dskhoaphien, string keyxt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetxmlThongdiep", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetxmlThongdiepAsync(string mst, string MTDiep);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.GetXMLResponse> GetXMLAsync(WSInterTRCA2.GetXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXML_MTT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSInterTRCA2.GetXML_MTTResponse> GetXML_MTTAsync(WSInterTRCA2.GetXML_MTTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Thongdiep
    {
        
        private string pBanField;
        
        private string mNGuiField;
        
        private string mNNhanField;
        
        private string mLTDiepField;
        
        private string mTDiepField;
        
        private string mTDTChieuField;
        
        private string mSTField;
        
        private string sLuongField;
        
        private string dLieuField;
        
        private string id_DLieuField;
        
        private string cKSNNTField;
        
        private int checkDLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PBan
        {
            get
            {
                return this.pBanField;
            }
            set
            {
                this.pBanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MNGui
        {
            get
            {
                return this.mNGuiField;
            }
            set
            {
                this.mNGuiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MNNhan
        {
            get
            {
                return this.mNNhanField;
            }
            set
            {
                this.mNNhanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MLTDiep
        {
            get
            {
                return this.mLTDiepField;
            }
            set
            {
                this.mLTDiepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MTDiep
        {
            get
            {
                return this.mTDiepField;
            }
            set
            {
                this.mTDiepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MTDTChieu
        {
            get
            {
                return this.mTDTChieuField;
            }
            set
            {
                this.mTDTChieuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MST
        {
            get
            {
                return this.mSTField;
            }
            set
            {
                this.mSTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SLuong
        {
            get
            {
                return this.sLuongField;
            }
            set
            {
                this.sLuongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DLieu
        {
            get
            {
                return this.dLieuField;
            }
            set
            {
                this.dLieuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Id_DLieu
        {
            get
            {
                return this.id_DLieuField;
            }
            set
            {
                this.id_DLieuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CKSNNT
        {
            get
            {
                return this.cKSNNTField;
            }
            set
            {
                this.cKSNNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int CheckDL
        {
            get
            {
                return this.checkDLField;
            }
            set
            {
                this.checkDLField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_UpdateRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlthue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idMessage;
        
        public LayKQThongdiep_TCT_UpdateRequest()
        {
        }
        
        public LayKQThongdiep_TCT_UpdateRequest(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            this.AuthHeader = AuthHeader;
            this.xmlthue = xmlthue;
            this.base64 = base64;
            this.idMessage = idMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int LayKQThongdiep_TCT_UpdateResult;
        
        public LayKQThongdiep_TCT_UpdateResponse()
        {
        }
        
        public LayKQThongdiep_TCT_UpdateResponse(int LayKQThongdiep_TCT_UpdateResult)
        {
            this.LayKQThongdiep_TCT_UpdateResult = LayKQThongdiep_TCT_UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Test", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_TestRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlthue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idMessage;
        
        public LayKQThongdiep_TCT_TestRequest()
        {
        }
        
        public LayKQThongdiep_TCT_TestRequest(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            this.AuthHeader = AuthHeader;
            this.xmlthue = xmlthue;
            this.base64 = base64;
            this.idMessage = idMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_TestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int LayKQThongdiep_TCT_TestResult;
        
        public LayKQThongdiep_TCT_TestResponse()
        {
        }
        
        public LayKQThongdiep_TCT_TestResponse(int LayKQThongdiep_TCT_TestResult)
        {
            this.LayKQThongdiep_TCT_TestResult = LayKQThongdiep_TCT_TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Test_new", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_Test_newRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlthue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idMessage;
        
        public LayKQThongdiep_TCT_Test_newRequest()
        {
        }
        
        public LayKQThongdiep_TCT_Test_newRequest(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            this.AuthHeader = AuthHeader;
            this.xmlthue = xmlthue;
            this.base64 = base64;
            this.idMessage = idMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Test_newResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_Test_newResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int LayKQThongdiep_TCT_Test_newResult;
        
        public LayKQThongdiep_TCT_Test_newResponse()
        {
        }
        
        public LayKQThongdiep_TCT_Test_newResponse(int LayKQThongdiep_TCT_Test_newResult)
        {
            this.LayKQThongdiep_TCT_Test_newResult = LayKQThongdiep_TCT_Test_newResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Guithongdiep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuithongdiepRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Noidungthongdiep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        public GuithongdiepRequest()
        {
        }
        
        public GuithongdiepRequest(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            this.AuthHeader = AuthHeader;
            this.Noidungthongdiep = Noidungthongdiep;
            this.base64 = base64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GuithongdiepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GuithongdiepResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GuithongdiepResult;
        
        public GuithongdiepResponse()
        {
        }
        
        public GuithongdiepResponse(string GuithongdiepResult)
        {
            this.GuithongdiepResult = GuithongdiepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiepRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Khoaphien;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MST;
        
        public LayKQThongdiepRequest()
        {
        }
        
        public LayKQThongdiepRequest(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien, string MST)
        {
            this.AuthHeader = AuthHeader;
            this.Khoaphien = Khoaphien;
            this.MST = MST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiepResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string LayKQThongdiepResult;
        
        public LayKQThongdiepResponse()
        {
        }
        
        public LayKQThongdiepResponse(string LayKQThongdiepResult)
        {
            this.LayKQThongdiepResult = LayKQThongdiepResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class LayLogtruyennhan_TCGPResponseLayLogtruyennhan_TCGPResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayLogtruyennhan_TCGP", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayLogtruyennhan_TCGPRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MST;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string tungay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string denngay;
        
        public LayLogtruyennhan_TCGPRequest()
        {
        }
        
        public LayLogtruyennhan_TCGPRequest(WSInterTRCA2.AuthHeader AuthHeader, string MST, string tungay, string denngay)
        {
            this.AuthHeader = AuthHeader;
            this.MST = MST;
            this.tungay = tungay;
            this.denngay = denngay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayLogtruyennhan_TCGPResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayLogtruyennhan_TCGPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSInterTRCA2.LayLogtruyennhan_TCGPResponseLayLogtruyennhan_TCGPResult LayLogtruyennhan_TCGPResult;
        
        public LayLogtruyennhan_TCGPResponse()
        {
        }
        
        public LayLogtruyennhan_TCGPResponse(WSInterTRCA2.LayLogtruyennhan_TCGPResponseLayLogtruyennhan_TCGPResult LayLogtruyennhan_TCGPResult)
        {
            this.LayLogtruyennhan_TCGPResult = LayLogtruyennhan_TCGPResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class LayLogtruyennhan_TVanResponseLayLogtruyennhan_TVanResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayLogtruyennhan_TVan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayLogtruyennhan_TVanRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tungay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string denngay;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int tieuchi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string MST;
        
        public LayLogtruyennhan_TVanRequest()
        {
        }
        
        public LayLogtruyennhan_TVanRequest(WSInterTRCA2.AuthHeader AuthHeader, string tungay, string denngay, int tieuchi, string MST)
        {
            this.AuthHeader = AuthHeader;
            this.tungay = tungay;
            this.denngay = denngay;
            this.tieuchi = tieuchi;
            this.MST = MST;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayLogtruyennhan_TVanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayLogtruyennhan_TVanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSInterTRCA2.LayLogtruyennhan_TVanResponseLayLogtruyennhan_TVanResult LayLogtruyennhan_TVanResult;
        
        public LayLogtruyennhan_TVanResponse()
        {
        }
        
        public LayLogtruyennhan_TVanResponse(WSInterTRCA2.LayLogtruyennhan_TVanResponseLayLogtruyennhan_TVanResult LayLogtruyennhan_TVanResult)
        {
            this.LayLogtruyennhan_TVanResult = LayLogtruyennhan_TVanResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Layphanhoi206_khoaphienResponseLayphanhoi206_khoaphienResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Layphanhoi206_khoaphien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Layphanhoi206_khoaphienRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Khoaphien;
        
        public Layphanhoi206_khoaphienRequest()
        {
        }
        
        public Layphanhoi206_khoaphienRequest(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien)
        {
            this.AuthHeader = AuthHeader;
            this.Khoaphien = Khoaphien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Layphanhoi206_khoaphienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Layphanhoi206_khoaphienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSInterTRCA2.Layphanhoi206_khoaphienResponseLayphanhoi206_khoaphienResult Layphanhoi206_khoaphienResult;
        
        public Layphanhoi206_khoaphienResponse()
        {
        }
        
        public Layphanhoi206_khoaphienResponse(WSInterTRCA2.Layphanhoi206_khoaphienResponseLayphanhoi206_khoaphienResult Layphanhoi206_khoaphienResult)
        {
            this.Layphanhoi206_khoaphienResult = Layphanhoi206_khoaphienResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class LayketquathongdiepTQ_khoaphienResponseLayketquathongdiepTQ_khoaphienResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayketquathongdiepTQ_khoaphien", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayketquathongdiepTQ_khoaphienRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Khoaphien;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MSTTCGP;
        
        public LayketquathongdiepTQ_khoaphienRequest()
        {
        }
        
        public LayketquathongdiepTQ_khoaphienRequest(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien, string MSTTCGP)
        {
            this.AuthHeader = AuthHeader;
            this.Khoaphien = Khoaphien;
            this.MSTTCGP = MSTTCGP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayketquathongdiepTQ_khoaphienResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayketquathongdiepTQ_khoaphienResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSInterTRCA2.LayketquathongdiepTQ_khoaphienResponseLayketquathongdiepTQ_khoaphienResult LayketquathongdiepTQ_khoaphienResult;
        
        public LayketquathongdiepTQ_khoaphienResponse()
        {
        }
        
        public LayketquathongdiepTQ_khoaphienResponse(WSInterTRCA2.LayketquathongdiepTQ_khoaphienResponseLayketquathongdiepTQ_khoaphienResult LayketquathongdiepTQ_khoaphienResult)
        {
            this.LayketquathongdiepTQ_khoaphienResult = LayketquathongdiepTQ_khoaphienResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class LayketquathongdiepTQ_Khoaphien_prefixResponseLayketquathongdiepTQ_Khoaphien_prefixResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayketquathongdiepTQ_Khoaphien_prefix", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayketquathongdiepTQ_Khoaphien_prefixRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Khoaphien_prefix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MSTTCGP;
        
        public LayketquathongdiepTQ_Khoaphien_prefixRequest()
        {
        }
        
        public LayketquathongdiepTQ_Khoaphien_prefixRequest(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien_prefix, string MSTTCGP)
        {
            this.AuthHeader = AuthHeader;
            this.Khoaphien_prefix = Khoaphien_prefix;
            this.MSTTCGP = MSTTCGP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayketquathongdiepTQ_Khoaphien_prefixResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayketquathongdiepTQ_Khoaphien_prefixResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixResponseLayketquathongdiepTQ_Khoaphien_prefixResult LayketquathongdiepTQ_Khoaphien_prefixResult;
        
        public LayketquathongdiepTQ_Khoaphien_prefixResponse()
        {
        }
        
        public LayketquathongdiepTQ_Khoaphien_prefixResponse(WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixResponseLayketquathongdiepTQ_Khoaphien_prefixResult LayketquathongdiepTQ_Khoaphien_prefixResult)
        {
            this.LayketquathongdiepTQ_Khoaphien_prefixResult = LayketquathongdiepTQ_Khoaphien_prefixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Update_2024", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_Update_2024Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string xmlthue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string idMessage;
        
        public LayKQThongdiep_TCT_Update_2024Request()
        {
        }
        
        public LayKQThongdiep_TCT_Update_2024Request(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            this.AuthHeader = AuthHeader;
            this.xmlthue = xmlthue;
            this.base64 = base64;
            this.idMessage = idMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LayKQThongdiep_TCT_Update_2024Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LayKQThongdiep_TCT_Update_2024Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int LayKQThongdiep_TCT_Update_2024Result;
        
        public LayKQThongdiep_TCT_Update_2024Response()
        {
        }
        
        public LayKQThongdiep_TCT_Update_2024Response(int LayKQThongdiep_TCT_Update_2024Result)
        {
            this.LayKQThongdiep_TCT_Update_2024Result = LayKQThongdiep_TCT_Update_2024Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Guithongdiep_MTDiep", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Guithongdiep_MTDiepRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Noidungthongdiep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        public Guithongdiep_MTDiepRequest()
        {
        }
        
        public Guithongdiep_MTDiepRequest(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            this.AuthHeader = AuthHeader;
            this.Noidungthongdiep = Noidungthongdiep;
            this.base64 = base64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Guithongdiep_MTDiepResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Guithongdiep_MTDiepResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Guithongdiep_MTDiepResult;
        
        public Guithongdiep_MTDiepResponse()
        {
        }
        
        public Guithongdiep_MTDiepResponse(string Guithongdiep_MTDiepResult)
        {
            this.Guithongdiep_MTDiepResult = Guithongdiep_MTDiepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Guithongdiep2024", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Guithongdiep2024Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Noidungthongdiep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int base64;
        
        public Guithongdiep2024Request()
        {
        }
        
        public Guithongdiep2024Request(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            this.AuthHeader = AuthHeader;
            this.Noidungthongdiep = Noidungthongdiep;
            this.base64 = base64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Guithongdiep2024Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Guithongdiep2024Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Guithongdiep2024Result;
        
        public Guithongdiep2024Response()
        {
        }
        
        public Guithongdiep2024Response(string Guithongdiep2024Result)
        {
            this.Guithongdiep2024Result = Guithongdiep2024Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class LayKQTruyennhantokhaichungtuResponseLayKQTruyennhantokhaichungtuResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXMLRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string khoaphien;
        
        public GetXMLRequest()
        {
        }
        
        public GetXMLRequest(WSInterTRCA2.AuthHeader AuthHeader, string khoaphien)
        {
            this.AuthHeader = AuthHeader;
            this.khoaphien = khoaphien;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetXMLResult;
        
        public GetXMLResponse()
        {
        }
        
        public GetXMLResponse(string GetXMLResult)
        {
            this.GetXMLResult = GetXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXML_MTT", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXML_MTTRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WSInterTRCA2.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string invoiceid;
        
        public GetXML_MTTRequest()
        {
        }
        
        public GetXML_MTTRequest(WSInterTRCA2.AuthHeader AuthHeader, string invoiceid)
        {
            this.AuthHeader = AuthHeader;
            this.invoiceid = invoiceid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetXML_MTTResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetXML_MTTResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetXML_MTTResult;
        
        public GetXML_MTTResponse()
        {
        }
        
        public GetXML_MTTResponse(string GetXML_MTTResult)
        {
            this.GetXML_MTTResult = GetXML_MTTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WSInterTRCA2SoapChannel : WSInterTRCA2.WSInterTRCA2Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WSInterTRCA2SoapClient : System.ServiceModel.ClientBase<WSInterTRCA2.WSInterTRCA2Soap>, WSInterTRCA2.WSInterTRCA2Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSInterTRCA2SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSInterTRCA2SoapClient.GetBindingForEndpoint(endpointConfiguration), WSInterTRCA2SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSInterTRCA2SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSInterTRCA2SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSInterTRCA2SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSInterTRCA2SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSInterTRCA2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> VerifySignatureAsync(string xml, int base64)
        {
            return base.Channel.VerifySignatureAsync(xml, base64);
        }
        
        public System.Threading.Tasks.Task<string> LayKhoaphien_MTDiepAsync(string MTDiep)
        {
            return base.Channel.LayKhoaphien_MTDiepAsync(MTDiep);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_UpdateResponse> WSInterTRCA2.WSInterTRCA2Soap.LayKQThongdiep_TCT_UpdateAsync(WSInterTRCA2.LayKQThongdiep_TCT_UpdateRequest request)
        {
            return base.Channel.LayKQThongdiep_TCT_UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_UpdateResponse> LayKQThongdiep_TCT_UpdateAsync(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            WSInterTRCA2.LayKQThongdiep_TCT_UpdateRequest inValue = new WSInterTRCA2.LayKQThongdiep_TCT_UpdateRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.xmlthue = xmlthue;
            inValue.base64 = base64;
            inValue.idMessage = idMessage;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayKQThongdiep_TCT_UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_TestResponse> WSInterTRCA2.WSInterTRCA2Soap.LayKQThongdiep_TCT_TestAsync(WSInterTRCA2.LayKQThongdiep_TCT_TestRequest request)
        {
            return base.Channel.LayKQThongdiep_TCT_TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_TestResponse> LayKQThongdiep_TCT_TestAsync(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            WSInterTRCA2.LayKQThongdiep_TCT_TestRequest inValue = new WSInterTRCA2.LayKQThongdiep_TCT_TestRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.xmlthue = xmlthue;
            inValue.base64 = base64;
            inValue.idMessage = idMessage;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayKQThongdiep_TCT_TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Test_newResponse> WSInterTRCA2.WSInterTRCA2Soap.LayKQThongdiep_TCT_Test_newAsync(WSInterTRCA2.LayKQThongdiep_TCT_Test_newRequest request)
        {
            return base.Channel.LayKQThongdiep_TCT_Test_newAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Test_newResponse> LayKQThongdiep_TCT_Test_newAsync(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            WSInterTRCA2.LayKQThongdiep_TCT_Test_newRequest inValue = new WSInterTRCA2.LayKQThongdiep_TCT_Test_newRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.xmlthue = xmlthue;
            inValue.base64 = base64;
            inValue.idMessage = idMessage;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayKQThongdiep_TCT_Test_newAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.GuithongdiepResponse> WSInterTRCA2.WSInterTRCA2Soap.GuithongdiepAsync(WSInterTRCA2.GuithongdiepRequest request)
        {
            return base.Channel.GuithongdiepAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.GuithongdiepResponse> GuithongdiepAsync(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            WSInterTRCA2.GuithongdiepRequest inValue = new WSInterTRCA2.GuithongdiepRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Noidungthongdiep = Noidungthongdiep;
            inValue.base64 = base64;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).GuithongdiepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiepResponse> WSInterTRCA2.WSInterTRCA2Soap.LayKQThongdiepAsync(WSInterTRCA2.LayKQThongdiepRequest request)
        {
            return base.Channel.LayKQThongdiepAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiepResponse> LayKQThongdiepAsync(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien, string MST)
        {
            WSInterTRCA2.LayKQThongdiepRequest inValue = new WSInterTRCA2.LayKQThongdiepRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Khoaphien = Khoaphien;
            inValue.MST = MST;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayKQThongdiepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TCGPResponse> WSInterTRCA2.WSInterTRCA2Soap.LayLogtruyennhan_TCGPAsync(WSInterTRCA2.LayLogtruyennhan_TCGPRequest request)
        {
            return base.Channel.LayLogtruyennhan_TCGPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TCGPResponse> LayLogtruyennhan_TCGPAsync(WSInterTRCA2.AuthHeader AuthHeader, string MST, string tungay, string denngay)
        {
            WSInterTRCA2.LayLogtruyennhan_TCGPRequest inValue = new WSInterTRCA2.LayLogtruyennhan_TCGPRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.MST = MST;
            inValue.tungay = tungay;
            inValue.denngay = denngay;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayLogtruyennhan_TCGPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TVanResponse> WSInterTRCA2.WSInterTRCA2Soap.LayLogtruyennhan_TVanAsync(WSInterTRCA2.LayLogtruyennhan_TVanRequest request)
        {
            return base.Channel.LayLogtruyennhan_TVanAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayLogtruyennhan_TVanResponse> LayLogtruyennhan_TVanAsync(WSInterTRCA2.AuthHeader AuthHeader, string tungay, string denngay, int tieuchi, string MST)
        {
            WSInterTRCA2.LayLogtruyennhan_TVanRequest inValue = new WSInterTRCA2.LayLogtruyennhan_TVanRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.tungay = tungay;
            inValue.denngay = denngay;
            inValue.tieuchi = tieuchi;
            inValue.MST = MST;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayLogtruyennhan_TVanAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.Thongdiep> LaynoidungthongdiepAsync(string base64xml)
        {
            return base.Channel.LaynoidungthongdiepAsync(base64xml);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.Thongdiep> Laynoidungthongdiep_chuoixmlAsync(string chuoixml)
        {
            return base.Channel.Laynoidungthongdiep_chuoixmlAsync(chuoixml);
        }
        
        public System.Threading.Tasks.Task<string> LayKQPhanhoicuathue_ThongbaoAsync(string chuoixml, int base64)
        {
            return base.Channel.LayKQPhanhoicuathue_ThongbaoAsync(chuoixml, base64);
        }
        
        public System.Threading.Tasks.Task<string> TaoQRCodeHDAsync(string MSTNguoiban, string KHMSHDon, string KHHDon, string SHDon, string NLap, string Tongtienthanhtoan)
        {
            return base.Channel.TaoQRCodeHDAsync(MSTNguoiban, KHMSHDon, KHHDon, SHDon, NLap, Tongtienthanhtoan);
        }
        
        public System.Threading.Tasks.Task<string> Taothongdiepphanhoikythuat_TCTAsync(string ThongdiepTCT, string TTTNhanDL, int base64)
        {
            return base.Channel.Taothongdiepphanhoikythuat_TCTAsync(ThongdiepTCT, TTTNhanDL, base64);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.Layphanhoi206_khoaphienResponse> WSInterTRCA2.WSInterTRCA2Soap.Layphanhoi206_khoaphienAsync(WSInterTRCA2.Layphanhoi206_khoaphienRequest request)
        {
            return base.Channel.Layphanhoi206_khoaphienAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.Layphanhoi206_khoaphienResponse> Layphanhoi206_khoaphienAsync(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien)
        {
            WSInterTRCA2.Layphanhoi206_khoaphienRequest inValue = new WSInterTRCA2.Layphanhoi206_khoaphienRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Khoaphien = Khoaphien;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).Layphanhoi206_khoaphienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_khoaphienResponse> WSInterTRCA2.WSInterTRCA2Soap.LayketquathongdiepTQ_khoaphienAsync(WSInterTRCA2.LayketquathongdiepTQ_khoaphienRequest request)
        {
            return base.Channel.LayketquathongdiepTQ_khoaphienAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_khoaphienResponse> LayketquathongdiepTQ_khoaphienAsync(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien, string MSTTCGP)
        {
            WSInterTRCA2.LayketquathongdiepTQ_khoaphienRequest inValue = new WSInterTRCA2.LayketquathongdiepTQ_khoaphienRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Khoaphien = Khoaphien;
            inValue.MSTTCGP = MSTTCGP;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayketquathongdiepTQ_khoaphienAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixResponse> WSInterTRCA2.WSInterTRCA2Soap.LayketquathongdiepTQ_Khoaphien_prefixAsync(WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixRequest request)
        {
            return base.Channel.LayketquathongdiepTQ_Khoaphien_prefixAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixResponse> LayketquathongdiepTQ_Khoaphien_prefixAsync(WSInterTRCA2.AuthHeader AuthHeader, string Khoaphien_prefix, string MSTTCGP)
        {
            WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixRequest inValue = new WSInterTRCA2.LayketquathongdiepTQ_Khoaphien_prefixRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Khoaphien_prefix = Khoaphien_prefix;
            inValue.MSTTCGP = MSTTCGP;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayketquathongdiepTQ_Khoaphien_prefixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Response> WSInterTRCA2.WSInterTRCA2Soap.LayKQThongdiep_TCT_Update_2024Async(WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Request request)
        {
            return base.Channel.LayKQThongdiep_TCT_Update_2024Async(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Response> LayKQThongdiep_TCT_Update_2024Async(WSInterTRCA2.AuthHeader AuthHeader, string xmlthue, int base64, string idMessage)
        {
            WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Request inValue = new WSInterTRCA2.LayKQThongdiep_TCT_Update_2024Request();
            inValue.AuthHeader = AuthHeader;
            inValue.xmlthue = xmlthue;
            inValue.base64 = base64;
            inValue.idMessage = idMessage;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).LayKQThongdiep_TCT_Update_2024Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep_MTDiepResponse> WSInterTRCA2.WSInterTRCA2Soap.Guithongdiep_MTDiepAsync(WSInterTRCA2.Guithongdiep_MTDiepRequest request)
        {
            return base.Channel.Guithongdiep_MTDiepAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep_MTDiepResponse> Guithongdiep_MTDiepAsync(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            WSInterTRCA2.Guithongdiep_MTDiepRequest inValue = new WSInterTRCA2.Guithongdiep_MTDiepRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.Noidungthongdiep = Noidungthongdiep;
            inValue.base64 = base64;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).Guithongdiep_MTDiepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep2024Response> WSInterTRCA2.WSInterTRCA2Soap.Guithongdiep2024Async(WSInterTRCA2.Guithongdiep2024Request request)
        {
            return base.Channel.Guithongdiep2024Async(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.Guithongdiep2024Response> Guithongdiep2024Async(WSInterTRCA2.AuthHeader AuthHeader, string Noidungthongdiep, int base64)
        {
            WSInterTRCA2.Guithongdiep2024Request inValue = new WSInterTRCA2.Guithongdiep2024Request();
            inValue.AuthHeader = AuthHeader;
            inValue.Noidungthongdiep = Noidungthongdiep;
            inValue.base64 = base64;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).Guithongdiep2024Async(inValue);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.LayKQTruyennhantokhaichungtuResponseLayKQTruyennhantokhaichungtuResult> LayKQTruyennhantokhaichungtuAsync(string MaDV, string dskhoaphien, string keyxt)
        {
            return base.Channel.LayKQTruyennhantokhaichungtuAsync(MaDV, dskhoaphien, keyxt);
        }
        
        public System.Threading.Tasks.Task<string> GetxmlThongdiepAsync(string mst, string MTDiep)
        {
            return base.Channel.GetxmlThongdiepAsync(mst, MTDiep);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.GetXMLResponse> WSInterTRCA2.WSInterTRCA2Soap.GetXMLAsync(WSInterTRCA2.GetXMLRequest request)
        {
            return base.Channel.GetXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.GetXMLResponse> GetXMLAsync(WSInterTRCA2.AuthHeader AuthHeader, string khoaphien)
        {
            WSInterTRCA2.GetXMLRequest inValue = new WSInterTRCA2.GetXMLRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.khoaphien = khoaphien;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).GetXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSInterTRCA2.GetXML_MTTResponse> WSInterTRCA2.WSInterTRCA2Soap.GetXML_MTTAsync(WSInterTRCA2.GetXML_MTTRequest request)
        {
            return base.Channel.GetXML_MTTAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSInterTRCA2.GetXML_MTTResponse> GetXML_MTTAsync(WSInterTRCA2.AuthHeader AuthHeader, string invoiceid)
        {
            WSInterTRCA2.GetXML_MTTRequest inValue = new WSInterTRCA2.GetXML_MTTRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.invoiceid = invoiceid;
            return ((WSInterTRCA2.WSInterTRCA2Soap)(this)).GetXML_MTTAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSInterTRCA2Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSInterTRCA2Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSInterTRCA2Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://servicetvan.nacencomm.vn/WSInterTRCA2.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSInterTRCA2Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://servicetvan.nacencomm.vn/WSInterTRCA2.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSInterTRCA2Soap,
            
            WSInterTRCA2Soap12,
        }
    }
}
