//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiSign
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiSign.wsCA2EinvoiceSoap")]
    public interface wsCA2EinvoiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2KySo_HD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2KySo_HDAsync(string base64xml, string MasothueNBH, string serialnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2KyGuiYCCM_HD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2KyGuiYCCM_HDAsync(string base64xml, string serialnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2KyGuiTCT_HDKM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2KyGuiTCT_HDKMAsync(string base64XML, string serialnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2GuiYCCM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2GuiYCCMAsync(string xmlSigned, string masothue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2GuiBangke_MTTien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CA2GuiBangke_MTTienAsync(string lstData, string masothue, string serialnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2GuiTBSS_HD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2GuiTBSS_HDAsync(string MaCQTQL, string TenCQTQL, string Diadanh, string Masothue, string TenNNT, string KHMSHdon, string KHHDon, string Sohoadon, string NgayHD, string MaCQT, string LoaiHDAP, string TChatTBao, string Lydo, string Serialnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CA2KyGuitokhaiDK_TCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<object> CA2KyGuitokhaiDK_TCTAsync(string base64xmltokhai, string serialno, string masothue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface wsCA2EinvoiceSoapChannel : ApiSign.wsCA2EinvoiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class wsCA2EinvoiceSoapClient : System.ServiceModel.ClientBase<ApiSign.wsCA2EinvoiceSoap>, ApiSign.wsCA2EinvoiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsCA2EinvoiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsCA2EinvoiceSoapClient.GetBindingForEndpoint(endpointConfiguration), wsCA2EinvoiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCA2EinvoiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsCA2EinvoiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCA2EinvoiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsCA2EinvoiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsCA2EinvoiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<object> CA2KySo_HDAsync(string base64xml, string MasothueNBH, string serialnumber)
        {
            return base.Channel.CA2KySo_HDAsync(base64xml, MasothueNBH, serialnumber);
        }
        
        public System.Threading.Tasks.Task<object> CA2KyGuiYCCM_HDAsync(string base64xml, string serialnumber)
        {
            return base.Channel.CA2KyGuiYCCM_HDAsync(base64xml, serialnumber);
        }
        
        public System.Threading.Tasks.Task<object> CA2KyGuiTCT_HDKMAsync(string base64XML, string serialnumber)
        {
            return base.Channel.CA2KyGuiTCT_HDKMAsync(base64XML, serialnumber);
        }
        
        public System.Threading.Tasks.Task<object> CA2GuiYCCMAsync(string xmlSigned, string masothue)
        {
            return base.Channel.CA2GuiYCCMAsync(xmlSigned, masothue);
        }
        
        public System.Threading.Tasks.Task<string> CA2GuiBangke_MTTienAsync(string lstData, string masothue, string serialnumber)
        {
            return base.Channel.CA2GuiBangke_MTTienAsync(lstData, masothue, serialnumber);
        }
        
        public System.Threading.Tasks.Task<object> CA2GuiTBSS_HDAsync(string MaCQTQL, string TenCQTQL, string Diadanh, string Masothue, string TenNNT, string KHMSHdon, string KHHDon, string Sohoadon, string NgayHD, string MaCQT, string LoaiHDAP, string TChatTBao, string Lydo, string Serialnumber)
        {
            return base.Channel.CA2GuiTBSS_HDAsync(MaCQTQL, TenCQTQL, Diadanh, Masothue, TenNNT, KHMSHdon, KHHDon, Sohoadon, NgayHD, MaCQT, LoaiHDAP, TChatTBao, Lydo, Serialnumber);
        }
        
        public System.Threading.Tasks.Task<object> CA2KyGuitokhaiDK_TCTAsync(string base64xmltokhai, string serialno, string masothue)
        {
            return base.Channel.CA2KyGuitokhaiDK_TCTAsync(base64xmltokhai, serialno, masothue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCA2EinvoiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCA2EinvoiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsCA2EinvoiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://apisignhd_pro.nacencomm.vn/wsCA2Einvoice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsCA2EinvoiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://apisignhd_pro.nacencomm.vn/wsCA2Einvoice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsCA2EinvoiceSoap,
            
            wsCA2EinvoiceSoap12,
        }
    }
}
