ALTER TABLE hoa_don add giam_thue_phan_tram REAL
ALTER TABLE hoa_don add giam_thue_ty_le REAL
ALTER TABLE hoa_don add giam_thue_thanh_tien decimal(21,6)
ALTER TABLE hoa_don add giam_thue_ghi_chu NVARCHAR(1000)
GO

ALTER procedure [dbo].[hoa_don_insert]
    @donvi_ma_dv nvarchar (200),
    @phien_ban nvarchar (20),
    @ten_hoa_don nvarchar (200),
    @hoa_don_dang_ky_phat_hanh_mau_so nvarchar (20),
    @hoa_don_dang_ky_phat_hanh_ky_hieu nvarchar (20),
    @loai_hoa_don_ct_id int,
    @so_hoa_don nvarchar (200),
    @ma_so_hoa_don nvarchar (200),
    @ma_so_hoa_don_mtt NVARCHAR(200),
    @ngay_hoa_don date,
    @loai_tien nvarchar (20)='VND',
    @ty_gia decimal,
    @nguoi_ban_mst nvarchar (200),
    @nguoi_ban_ten_donvi nvarchar (2000),
    @nguoi_ban_dia_chi nvarchar (2000),
    @nguoi_ban_stk nvarchar (2000),
    @nguoi_ban_ngan_hang nvarchar (2000),
    @nguoi_ban_dien_thoai nvarchar (2000),
    @nguoi_ban_fax nvarchar (2000),
    @nguoi_ban_email nvarchar (2000),
    @nguoi_ban_website nvarchar (2000),
    @nguoi_mua_ten_donvi nvarchar (2000),
    @nguoi_mua_mst nvarchar (200),
    @nguoi_mua_ten nvarchar (2000),
    @nguoi_mua_dia_chi nvarchar (2000),
    @nguoi_mua_stk nvarchar (2000),
    @nguoi_mua_ngan_hang nvarchar (2000),
    @nguoi_mua_dien_thoai nvarchar (2000),
    @nguoi_mua_fax nvarchar (2000),
    @nguoi_mua_email nvarchar (2000),
    @nguoi_mua_website nvarchar (2000),
    @nguoi_mua_cccd NVARCHAR(20),
    @hinh_thuc_tt nvarchar (200),
    @hoa_don_trang_thai_id int,
    @tong_tien_truong_thue decimal,
    @tong_tien_thue decimal,
    @tong_tien_phi decimal,
    @tong_tien_thanh_toan decimal,
    @tong_tien_chu nvarchar (510),
    @ma_tra_cuu nvarchar (200),
    @qr_code nvarchar (200),
    @is_deleted bit,
    @created_time datetime,
    @created_user_id int,
    @last_modified_times datetime,
    @last_modified_user_id int,
    @nguoi_tao nvarchar (2000),
    @ngay_tao datetime,
    @hoa_don_hinh_thuc_id int,
    @hoa_don_id_goc int,
    @ket_qua_phat_hanh nvarchar(max),
    @hoa_don_ly_do_dieu_chinh_id INT,
    @is_ky_so_succes BIT,
    @phat_hanh_uuid NVARCHAR(100),
    @user_id_phathanh INT,
    @xuat_kho_vc_lenh_dieu_dong_noi_bo nvarchar (300),
    @xuat_kho_dl_hop_dong_kinh_te_so nvarchar (300),
    @xuat_kho_dl_hop_dong_ngay datetime,
    @xuat_kho_hop_dong_so nvarchar (300),
    @xuat_kho_nguoi_xuat_hang nvarchar (300),
    @xuat_kho_nguoi_van_chuyen nvarchar (300),
    @xuat_kho_phuong_tien_van_chuyen nvarchar (300),
    @hoa_don_hinh_thuc_code NVARCHAR(10),
    @phat_hanh_ma_ketqua_cqt nvarchar(100),
    @hoa_don_dang_ky_phat_hanh_mau_so_goc NVARCHAR(100),
    @hoa_don_dang_ky_phat_hanh_ky_hieu_goc NVARCHAR(100),
    @ma_so_hoa_don_goc NVARCHAR(10),
    @ngay_hoa_don_goc DATE,
    @hoa_don_nghi_dinh_id INT,
    @hoa_don_nghi_dinh_id_goc INT,
    @hoa_don_ids_thaythe_dieuchinh NVARCHAR(1000)='',
    @tt_nuoc_ma_bill NVARCHAR(15)='',
    @tt_nuoc_ngay_doc_thang_truoc NVARCHAR(15)='',
    @tt_nuoc_ngay_doc_thang_nay NVARCHAR(15)='',
    @tt_nuoc_so_cuong NVARCHAR(15)='',
    @tt_nuoc_ma_nguoi_mua NVARCHAR(15)='',
    @tt_nuoc_chi_so_thang_truoc NVARCHAR(15)='',
    @tt_nuoc_chi_so_thang_ngay NVARCHAR(15)='',
    @tt_nuoc_ma_nuoc NVARCHAR(15)='',
    @tt_nuoc_tong_so_ngay NVARCHAR(15)='',
    @tt_nuoc_tong_tieu_thu NVARCHAR(15)='',
    @tt_nuoc_so_ho NVARCHAR(15)='',
    @tt_nuoc_serial_dong_ho NVARCHAR(15)='',
    @ma_dai_ly NVARCHAR(100)='',
    @ten_dai_ly NVARCHAR(1000)='',
    @tong_tien_chiet_khau decimal=0,
    @invoice_id nvarchar(50)='',
    @vender_id NVARCHAR(50)='',
    @so_tien_tang_giam INT=0,
    @so_tien_tang_giam_tien_hang INT=0,
    @so_tien_tang_giam_tien_thue INT=0,
    @ma_dv_ngan_sach NVARCHAR(100)='',
    @giam_thue_phan_tram REAL=0,
    @giam_thue_ty_le REAL=0,
    @giam_thue_thanh_tien DECIMAL=0,
    @giam_thue_ghi_chu nvarchar(1000)=''
as
begin
    if ISNULL(@loai_tien,'')='' SET @loai_tien='VND'
    insert into hoa_don
        (donvi_ma_dv,
        phien_ban,
        ten_hoa_don,
        hoa_don_dang_ky_phat_hanh_mau_so,
        hoa_don_dang_ky_phat_hanh_ky_hieu,
        loai_hoa_don_ct_id,
        so_hoa_don,
        ma_so_hoa_don,
        ngay_hoa_don,
        loai_tien,
        ty_gia,
        nguoi_ban_mst,
        nguoi_ban_ten_donvi,
        nguoi_ban_dia_chi,
        nguoi_ban_stk,
        nguoi_ban_ngan_hang,
        nguoi_ban_dien_thoai,
        nguoi_ban_fax,
        nguoi_ban_email,
        nguoi_ban_website,
        nguoi_mua_ten_donvi,
        nguoi_mua_mst,
        nguoi_mua_ten,
        nguoi_mua_dia_chi,
        nguoi_mua_stk,
        nguoi_mua_ngan_hang,
        nguoi_mua_dien_thoai,
        nguoi_mua_fax,
        nguoi_mua_email,
        nguoi_mua_website,
        hinh_thuc_tt,
        hoa_don_trang_thai_id,
        tong_tien_truong_thue,
        tong_tien_thue,
        tong_tien_phi,
        tong_tien_thanh_toan,
        tong_tien_chu,
        ma_tra_cuu,
        qr_code,
        is_deleted,
        created_time,
        created_user_id,
        last_modified_times,
        last_modified_user_id,
        nguoi_tao,
        ngay_tao,
        hoa_don_hinh_thuc_id,
        hoa_don_id_goc,
        ket_qua_phat_hanh,
        hoa_don_ly_do_dieu_chinh_id,
        is_ky_so_succes,
        phat_hanh_uuid,
        user_id_phathanh,
        xuat_kho_vc_lenh_dieu_dong_noi_bo,
        xuat_kho_dl_hop_dong_kinh_te_so,
        xuat_kho_dl_hop_dong_ngay,
        xuat_kho_hop_dong_so,
        xuat_kho_nguoi_xuat_hang,
        xuat_kho_nguoi_van_chuyen,
        xuat_kho_phuong_tien_van_chuyen,
        ma_so_hoa_don_mtt,
        nguoi_mua_cccd,
        hoa_don_hinh_thuc_code,
        phat_hanh_ma_ketqua_cqt,
        hoa_don_dang_ky_phat_hanh_mau_so_goc,
        hoa_don_dang_ky_phat_hanh_ky_hieu_goc,
        ma_so_hoa_don_goc,
        ngay_hoa_don_goc,
        hoa_don_nghi_dinh_id,
        hoa_don_nghi_dinh_id_goc,
        hoa_don_ids_thaythe_dieuchinh,
        tt_nuoc_ma_bill,
        tt_nuoc_ngay_doc_thang_truoc,
        tt_nuoc_ngay_doc_thang_nay,
        tt_nuoc_so_cuong,
        tt_nuoc_ma_nguoi_mua,
        tt_nuoc_chi_so_thang_truoc,
        tt_nuoc_chi_so_thang_ngay,
        tt_nuoc_ma_nuoc,
        tt_nuoc_tong_so_ngay,
        tt_nuoc_tong_tieu_thu,
        tt_nuoc_so_ho,
        tt_nuoc_serial_dong_ho,
        ma_dai_ly,
        ten_dai_ly,
        tong_tien_chiet_khau,
        invoice_id,
        vender_id,
        so_tien_tang_giam,
        so_tien_tang_giam_tien_hang,
        so_tien_tang_giam_tien_thue ,
        ma_dv_ngan_sach,
        giam_thue_phan_tram ,
        giam_thue_ty_le ,
        giam_thue_thanh_tien ,
        giam_thue_ghi_chu
        )
    values
        (@donvi_ma_dv,
            @phien_ban,
            @ten_hoa_don,
            @hoa_don_dang_ky_phat_hanh_mau_so,
            @hoa_don_dang_ky_phat_hanh_ky_hieu,
            @loai_hoa_don_ct_id,
            @so_hoa_don,
            @ma_so_hoa_don,
            @ngay_hoa_don,
            @loai_tien,
            @ty_gia,
            @nguoi_ban_mst,
            @nguoi_ban_ten_donvi,
            @nguoi_ban_dia_chi,
            @nguoi_ban_stk,
            @nguoi_ban_ngan_hang,
            @nguoi_ban_dien_thoai,
            @nguoi_ban_fax,
            @nguoi_ban_email,
            @nguoi_ban_website,
            @nguoi_mua_ten_donvi,
            @nguoi_mua_mst,
            @nguoi_mua_ten,
            @nguoi_mua_dia_chi,
            @nguoi_mua_stk,
            @nguoi_mua_ngan_hang,
            @nguoi_mua_dien_thoai,
            @nguoi_mua_fax,
            @nguoi_mua_email,
            @nguoi_mua_website,
            @hinh_thuc_tt,
            @hoa_don_trang_thai_id,
            @tong_tien_truong_thue,
            @tong_tien_thue,
            @tong_tien_phi,
            @tong_tien_thanh_toan,
            @tong_tien_chu,
            @ma_tra_cuu,
            @qr_code,
            @is_deleted,
            @created_time,
            @created_user_id,
            @last_modified_times,
            @last_modified_user_id,
            @nguoi_tao,
            @ngay_tao,
            @hoa_don_hinh_thuc_id,
            @hoa_don_id_goc,
            @ket_qua_phat_hanh,
            @hoa_don_ly_do_dieu_chinh_id,
            @is_ky_so_succes,
            @phat_hanh_uuid,
            @user_id_phathanh,
            @xuat_kho_vc_lenh_dieu_dong_noi_bo,
            @xuat_kho_dl_hop_dong_kinh_te_so,
            @xuat_kho_dl_hop_dong_ngay,
            @xuat_kho_hop_dong_so,
            @xuat_kho_nguoi_xuat_hang,
            @xuat_kho_nguoi_van_chuyen,
            @xuat_kho_phuong_tien_van_chuyen,
            @ma_so_hoa_don_mtt,
            @nguoi_mua_cccd,
            @hoa_don_hinh_thuc_code,
            @phat_hanh_ma_ketqua_cqt,
            @hoa_don_dang_ky_phat_hanh_mau_so_goc,
            @hoa_don_dang_ky_phat_hanh_ky_hieu_goc,
            @ma_so_hoa_don_goc,
            @ngay_hoa_don_goc,
            @hoa_don_nghi_dinh_id,
            @hoa_don_nghi_dinh_id_goc,
            @hoa_don_ids_thaythe_dieuchinh,
            @tt_nuoc_ma_bill,
            @tt_nuoc_ngay_doc_thang_truoc,
            @tt_nuoc_ngay_doc_thang_nay,
            @tt_nuoc_so_cuong,
            @tt_nuoc_ma_nguoi_mua,
            @tt_nuoc_chi_so_thang_truoc,
            @tt_nuoc_chi_so_thang_ngay,
            @tt_nuoc_ma_nuoc,
            @tt_nuoc_tong_so_ngay,
            @tt_nuoc_tong_tieu_thu,
            @tt_nuoc_so_ho,
            @tt_nuoc_serial_dong_ho,
            @ma_dai_ly ,
            @ten_dai_ly ,
            @tong_tien_chiet_khau,
            @invoice_id,
            @vender_id,
            @so_tien_tang_giam,
            @so_tien_tang_giam_tien_hang,
            @so_tien_tang_giam_tien_thue,
            @ma_dv_ngan_sach,
            @giam_thue_phan_tram,
            @giam_thue_ty_le ,
            @giam_thue_thanh_tien ,
            @giam_thue_ghi_chu
            )
    return @@identity
end
GO


ALTER procedure [dbo].[hoa_don_update]
    @id int,
    @donvi_ma_dv nvarchar (200),
    @phien_ban nvarchar (20),
    @ten_hoa_don nvarchar (200),
    @hoa_don_dang_ky_phat_hanh_mau_so nvarchar (20),
    @hoa_don_dang_ky_phat_hanh_ky_hieu nvarchar (20),
    @loai_hoa_don_ct_id int,
    @so_hoa_don nvarchar (200),
    @ma_so_hoa_don nvarchar (200),
    @ngay_hoa_don date,
    @loai_tien nvarchar (20),
    @ty_gia decimal,
    @nguoi_ban_mst nvarchar (200),
    @nguoi_ban_ten_donvi nvarchar (2000),
    @nguoi_ban_dia_chi nvarchar (2000),
    @nguoi_ban_stk nvarchar (2000),
    @nguoi_ban_ngan_hang nvarchar (2000),
    @nguoi_ban_dien_thoai nvarchar (2000),
    @nguoi_ban_fax nvarchar (2000),
    @nguoi_ban_email nvarchar (2000),
    @nguoi_ban_website nvarchar (2000),
    @nguoi_mua_ten_donvi nvarchar (2000),
    @nguoi_mua_mst nvarchar (200),
    @nguoi_mua_ten nvarchar (2000),
    @nguoi_mua_dia_chi nvarchar (2000),
    @nguoi_mua_stk nvarchar (2000),
    @nguoi_mua_ngan_hang nvarchar (2000),
    @nguoi_mua_dien_thoai nvarchar (2000),
    @nguoi_mua_fax nvarchar (2000),
    @nguoi_mua_email nvarchar (2000),
    @nguoi_mua_website nvarchar (2000),
    @hinh_thuc_tt nvarchar (200),
    @hoa_don_trang_thai_id int,
    @tong_tien_truong_thue decimal,
    @tong_tien_thue decimal,
    @tong_tien_phi decimal,
    @tong_tien_thanh_toan decimal,
    @tong_tien_chu nvarchar (510),
    @ma_tra_cuu nvarchar (200),
    @qr_code nvarchar (200),
    @last_modified_times datetime,
    @last_modified_user_id int,
    @nguoi_tao nvarchar (2000),
    @ngay_tao datetime,
    @hoa_don_hinh_thuc_id int,
    @hoa_don_id_goc int,
    @ket_qua_phat_hanh nvarchar (max),
    @hoa_don_ly_do_dieu_chinh_id int,
    @is_ky_so_succes bit,
    @phat_hanh_uuid nvarchar (200)='',
    @user_id_phathanh int=0,
    @xuat_kho_vc_lenh_dieu_dong_noi_bo nvarchar (300)='',
    @xuat_kho_dl_hop_dong_kinh_te_so nvarchar (300)='',
    @xuat_kho_dl_hop_dong_ngay datetime=null,
    @xuat_kho_hop_dong_so nvarchar (300)='',
    @xuat_kho_nguoi_xuat_hang nvarchar (300)='',
    @xuat_kho_nguoi_van_chuyen nvarchar (300)='',
    @xuat_kho_phuong_tien_van_chuyen nvarchar (300)='',
    @ma_so_hoa_don_mtt nvarchar(100),
    @nguoi_mua_cccd nvarchar(20),
    @hoa_don_hinh_thuc_code NVARCHAR(10),
    @phat_hanh_ma_ketqua_cqt nvarchar(100),
    @hoa_don_dang_ky_phat_hanh_mau_so_goc NVARCHAR(100),
    @hoa_don_dang_ky_phat_hanh_ky_hieu_goc NVARCHAR(100),
    @ma_so_hoa_don_goc NVARCHAR(10),
    @ngay_hoa_don_goc DATE,
    @hoa_don_nghi_dinh_id INT=123,
    @hoa_don_nghi_dinh_id_goc INT=123,
    @hoa_don_ids_thaythe_dieuchinh NVARCHAR(1000)='',
    @tt_nuoc_ma_bill NVARCHAR(15)='',
    @tt_nuoc_ngay_doc_thang_truoc NVARCHAR(15)='',
    @tt_nuoc_ngay_doc_thang_nay NVARCHAR(15)='',
    @tt_nuoc_so_cuong NVARCHAR(15)='',
    @tt_nuoc_ma_nguoi_mua NVARCHAR(15)='',
    @tt_nuoc_chi_so_thang_truoc NVARCHAR(15)='',
    @tt_nuoc_chi_so_thang_ngay NVARCHAR(15)='',
    @tt_nuoc_ma_nuoc NVARCHAR(15)='',
    @tt_nuoc_tong_so_ngay NVARCHAR(15)='',
    @tt_nuoc_tong_tieu_thu NVARCHAR(15)='',
    @tt_nuoc_so_ho NVARCHAR(15)='',
    @tt_nuoc_serial_dong_ho NVARCHAR(15)='',
    @ma_dai_ly NVARCHAR(100)='',
    @ten_dai_ly NVARCHAR(1000)='',
    @tong_tien_chiet_khau decimal=0,
    @invoice_id NVARCHAR(50)='',
    @vender_id nvarchar(50)='',
    @so_tien_tang_giam INT =0,
    @so_tien_tang_giam_tien_hang INT=0,
    @so_tien_tang_giam_tien_thue INT=0,
    @ma_dv_ngan_sach NVARCHAR(100)='',
    @giam_thue_phan_tram REAL=0,
    @giam_thue_ty_le REAL=0,
    @giam_thue_thanh_tien DECIMAL=0,
    @giam_thue_ghi_chu nvarchar(1000)=''
as
begin
    update hoa_don
	set
		donvi_ma_dv=@donvi_ma_dv,
		phien_ban=@phien_ban,
		ten_hoa_don=@ten_hoa_don,
		hoa_don_dang_ky_phat_hanh_mau_so=@hoa_don_dang_ky_phat_hanh_mau_so,
		hoa_don_dang_ky_phat_hanh_ky_hieu=@hoa_don_dang_ky_phat_hanh_ky_hieu,
		loai_hoa_don_ct_id=@loai_hoa_don_ct_id,
		so_hoa_don=@so_hoa_don,
		ma_so_hoa_don=@ma_so_hoa_don,
		ngay_hoa_don=@ngay_hoa_don,
		loai_tien=@loai_tien,
		ty_gia=@ty_gia,
		nguoi_ban_mst=@nguoi_ban_mst,
		nguoi_ban_ten_donvi=@nguoi_ban_ten_donvi,
		nguoi_ban_dia_chi=@nguoi_ban_dia_chi,
		nguoi_ban_stk=@nguoi_ban_stk,
		nguoi_ban_ngan_hang=@nguoi_ban_ngan_hang,
		nguoi_ban_dien_thoai=@nguoi_ban_dien_thoai,
		nguoi_ban_fax=@nguoi_ban_fax,
		nguoi_ban_email=@nguoi_ban_email,
		nguoi_ban_website=@nguoi_ban_website,
		nguoi_mua_ten_donvi=@nguoi_mua_ten_donvi,
		nguoi_mua_mst=@nguoi_mua_mst,
		nguoi_mua_ten=@nguoi_mua_ten,
		nguoi_mua_dia_chi=@nguoi_mua_dia_chi,
		nguoi_mua_stk=@nguoi_mua_stk,
		nguoi_mua_ngan_hang=@nguoi_mua_ngan_hang,
		nguoi_mua_dien_thoai=@nguoi_mua_dien_thoai,
		nguoi_mua_fax=@nguoi_mua_fax,
		nguoi_mua_email=@nguoi_mua_email,
		nguoi_mua_website=@nguoi_mua_website,
		hinh_thuc_tt=@hinh_thuc_tt,
		hoa_don_trang_thai_id=@hoa_don_trang_thai_id,
		tong_tien_truong_thue=@tong_tien_truong_thue,
		tong_tien_thue=@tong_tien_thue,
		tong_tien_phi=@tong_tien_phi,
		tong_tien_thanh_toan=@tong_tien_thanh_toan,
		tong_tien_chu=@tong_tien_chu,
		ma_tra_cuu=@ma_tra_cuu,
		qr_code=@qr_code,
		last_modified_times=@last_modified_times,
		last_modified_user_id=@last_modified_user_id,
		nguoi_tao=@nguoi_tao,
		ngay_tao=@ngay_tao,
		hoa_don_hinh_thuc_id=@hoa_don_hinh_thuc_id,
		hoa_don_id_goc=@hoa_don_id_goc,
		ket_qua_phat_hanh=@ket_qua_phat_hanh,
		hoa_don_ly_do_dieu_chinh_id=@hoa_don_ly_do_dieu_chinh_id,
		is_ky_so_succes=@is_ky_so_succes,
		phat_hanh_uuid=@phat_hanh_uuid,
		user_id_phathanh=@user_id_phathanh,
		xuat_kho_vc_lenh_dieu_dong_noi_bo=@xuat_kho_vc_lenh_dieu_dong_noi_bo,
		xuat_kho_dl_hop_dong_kinh_te_so=@xuat_kho_dl_hop_dong_kinh_te_so,
		xuat_kho_dl_hop_dong_ngay=@xuat_kho_dl_hop_dong_ngay,
		xuat_kho_hop_dong_so=@xuat_kho_hop_dong_so,
		xuat_kho_nguoi_xuat_hang=@xuat_kho_nguoi_xuat_hang,
		xuat_kho_nguoi_van_chuyen=@xuat_kho_nguoi_van_chuyen,
		xuat_kho_phuong_tien_van_chuyen=@xuat_kho_phuong_tien_van_chuyen,
        ma_so_hoa_don_mtt=@ma_so_hoa_don_mtt,
        nguoi_mua_cccd =@nguoi_mua_cccd,
        hoa_don_hinh_thuc_code =    @hoa_don_hinh_thuc_code,
		phat_hanh_ma_ketqua_cqt=@phat_hanh_ma_ketqua_cqt,
        hoa_don_dang_ky_phat_hanh_mau_so_goc=@hoa_don_dang_ky_phat_hanh_mau_so_goc,
        hoa_don_dang_ky_phat_hanh_ky_hieu_goc=@hoa_don_dang_ky_phat_hanh_ky_hieu_goc,
        ma_so_hoa_don_goc=@ma_so_hoa_don_goc,
        ngay_hoa_don_goc=@ngay_hoa_don_goc,
        hoa_don_nghi_dinh_id= @hoa_don_nghi_dinh_id,
        hoa_don_nghi_dinh_id_goc=hoa_don_nghi_dinh_id_goc,
        hoa_don_ids_thaythe_dieuchinh=@hoa_don_ids_thaythe_dieuchinh,
        tt_nuoc_ma_bill=@tt_nuoc_ma_bill,
		tt_nuoc_ngay_doc_thang_truoc=@tt_nuoc_ngay_doc_thang_truoc,
		tt_nuoc_ngay_doc_thang_nay=@tt_nuoc_ngay_doc_thang_nay,
		tt_nuoc_so_cuong=@tt_nuoc_so_cuong,
		tt_nuoc_ma_nguoi_mua=@tt_nuoc_ma_nguoi_mua,
		tt_nuoc_chi_so_thang_truoc=@tt_nuoc_chi_so_thang_truoc,
		tt_nuoc_chi_so_thang_ngay=@tt_nuoc_chi_so_thang_ngay,
		tt_nuoc_ma_nuoc=@tt_nuoc_ma_nuoc,
		tt_nuoc_tong_so_ngay=@tt_nuoc_tong_so_ngay,
		tt_nuoc_tong_tieu_thu=@tt_nuoc_tong_tieu_thu,
		tt_nuoc_so_ho=@tt_nuoc_so_ho,
		tt_nuoc_serial_dong_ho=@tt_nuoc_serial_dong_ho,
        ma_dai_ly=@ma_dai_ly,
        ten_dai_ly=@ten_dai_ly,
        tong_tien_chiet_khau=@tong_tien_chiet_khau,
        invoice_id=@invoice_id,
        vender_id=@vender_id,
        so_tien_tang_giam=@so_tien_tang_giam,
        so_tien_tang_giam_tien_hang=@so_tien_tang_giam_tien_hang,
        so_tien_tang_giam_tien_thue=@so_tien_tang_giam_tien_thue,
        ma_dv_ngan_sach=@ma_dv_ngan_sach,
        giam_thue_phan_tram=@giam_thue_phan_tram,
        giam_thue_ty_le=@giam_thue_ty_le,
        giam_thue_thanh_tien=@giam_thue_thanh_tien,
        giam_thue_ghi_chu=@giam_thue_ghi_chu
	where id=@id
end
GO
